### ISSUE TITLE
Besoin d'aide pour la transcription de article_f201 

### ISSUE THREAD

**Issue by HugoSchtr** [axellelecroq/apollinaire-project#14]
Bonsoir ! 
Je crée une issue à la place d'une pull request car cela me semble plus adapté pour ce cas. 
Le f201 du dossier de presse possède 4 articles, dont trois en allemand. N'étant pas germanophone, la police d'écriture du premier article (vue1) a rendu la transcription difficile. J'ai tout de même essayé de le transcrire, tant bien que mal. Il y a certainement des fautes partout. Je fais donc appel à votre aide pour m'aider dans cette tâche, s'il-vous-plait. Toutes les lettres et les mots m'ayant posé un soucis sont sont indiqués par un ?. La police d'écriture des articles 2 et 3 (vue2, vue3) m'a posé moins de problème, je pense que ces transcriptions sont OK. J'ai cependant eu quelques soucis pour lire le nom du journal du troisième article. 

N'hésitez pas à modifier directement le fichier en question ([apollinaire-project/dossierdepresse/article_f201.txt](https://github.com/axellelecroq/apollinaire-project/blob/corpus/dossierdepresse/article_f201.txt))

Je vais de ce pas ouvrir une branche pour qu'on puisse travailler dessus. 

Merci par avance !

**Comment by axellelecroq** [comment]
as-tu déjà crée une branche ? je ne la vois malheureusement pas.

**Comment by HugoSchtr** [comment]
Normalement elle est créée :)
-> transcription_article_f201
![transcription_article_f201_branch](https://user-images.githubusercontent.com/74325901/104652135-f3409800-56b8-11eb-950b-ea8e6401d170.png)

**Comment by axellelecroq** [comment]
En effet au temps pour moi !
j'ai corrigé l'article imprimé en écriture gothique et relu l'article en allemand à côté ;)

**Comment by HugoSchtr** [comment]
Super chouette ! Merci beaucoup :+1:

**Comment by HugoSchtr** [comment]
Si tout le monde est OK, on peut clore cette issue et faire une pull request pour merge article_f202.txt dans corpus.
Et sur ce, bonne nuit ! :)

**Comment by leaprs** [comment]
Je suis d'accord pour clore cette issue. N'ayant pas fait d'allemand, je ne vous serais pas d'une grande aide !

**Comment by ArsGeo** [comment]
De même que Léa !
