### ISSUE TITLE
Convention de nommage pour les fichiers

### ISSUE THREAD

**Issue by HugoSchtr** [axellelecroq/apollinaire-project#15]
Deuxième issue de la soirée ! 
Je fais appel à vous pour discuter d'une convention de nommage pour nos fichiers. 

A mon avis, nous devrions réfléchir à un système permettant de nommer les fichiers afin de bien les différencier. J'ai en effet peur qu'on puisse confondre par exemple le_pont_mirabeau.txt dans [apollinaire-project/poèmespubliés/](https://github.com/axellelecroq/apollinaire-project/tree/corpus/po%C3%A8mespubli%C3%A9s) et le_pont_mirabeau.txt dans [apollinaire-project/poèmesmanuscrits/](https://github.com/axellelecroq/apollinaire-project/tree/corpus/po%C3%A8mesmanuscrits). Pareil pour le dossier de presse, on ne retrouve pas la structure du document original quand on regarde le dossier.

Si vous êtes de cet avis, que serait-il nécessaire d'indiquer dans le nom du fichier ? Et dans quel ordre ? 

Pour le dossier de presse, j'ai pensé à quelque chose de simple par exemple : 
numérofolio_typededocument.txt
Mettre le numérofolio permettrait de garder la structure du document, et le typededocument nous indiquerait s'il s'agit d'une lettre ou d'un article de presse. 
Mais voilà, je pense qu'il serait plus simple de s'accorder sur une convention de nommage adapté à l'ensemble de notre corpus, car celle que j'ai proposé est tout de même spécifique au dossier de presse. 

Bonne soirée à vous :)

**Comment by axellelecroq** [comment]
Bonne remarque ! 
Peut-être que nous pourrions ajouter "man" dans le nom pour les poèmes manuscrits et "pub" pour les poèmes publiés ?

**Comment by HugoSchtr** [comment]
Oui je suis d'accord ! 

Pour le moment, le plus logique me semble être : 
* numeroFolio_?_identifiantDocument

Le ? est une question : Doit-on indiquer le titre du document contenu dans le folio dans le nom du fichier txt ? Au risque d'avoir des noms à rallonge ? Ou peut-on seulement se contenter de numeroFolio_identifiantDocument ? 

Par exemple, pour le folio 198 du dossier de presse : 
* f198_?_pre

("pre" pour dossier de presse)

Commencer par le numeroFolio permettrait de garder la structure du document original, on pourrait voir la voir directement dans les différents dossiers. Et cela nous simplifierait la tâche si nous voulons aller vérifier quelque chose sur Gallica-même. Par exemple, si j'ai un doute sur le f198 du dossier de presse, je sais qu'il correspond à la vue 198 du dossier de presse sur le viewer Gallica. 

Qu'en pensez-vous ? 

Bon weekend ! :)

**Comment by Juliettejns** [comment]
Bonjour!

Il vaut sans doute mieux éviter des noms à ralonge, je suis d'accord avec toi. Cependant, je pense qu'il serait également bien de voir assez rapidement le titre ou type du document (article ou lettre dans le cas du dossier de presse) sans avoir forcément besoin d'aller se référer à Gallica ou de lire la transcription en entier...

Le nom du fichier pourrait donc être numérofolio_identifiantDoc comme tu le proposes mais auquel cas, peut être ajouter au début du document quelque chose pour présenter un peu plus précisément le document par l'exemple, dans le cas d'un lettre du dossier de presse:

type de document: lettre
titre: lettre de Personne1 à Personne2

Pensez-vous que ça pourrait être intéressant?

Un bon dimanche à vous!!

**Comment by ArsGeo** [comment]
Je pense que ce que propose Juliette est intéressant. Concernant les poèmes manuscrits, il me semble que l'on s'était mis d'accord pour garder l'intégrité des textes que l'on push (un fichier par poème) mais nous pourrions aussi indiquer les folios concernés au début du nom, cela ne rallonge pas beaucoup celui-ci et permet d'aller vérifier plus rapidement sur Gallica.

**Comment by axellelecroq** [comment]
Je suis d'accord avec @Juliettejns aussi, néanmoins il s'agit que de lettres reçues par Apollinaire (sauf si je me trompe).
Il serait peut-être judicieux d'utiliser des abréviations afin d'indiquer dans quelle "collection" le fichier se situe : 
- dp pour dossier de presse
- pm pour poème manuscrit
-  pp pour poème publié
Il s'agit bien évidemment que d'une proposition !
Ainsi pour une lettre, cela serait : `dp_lettre_fernandfleuret` par exemple.

**Comment by HugoSchtr** [comment]
D'accord avec tes abréviations @axellelecroq ! Et prêt à les mettre en application. 

Cependant, mettre le nom de l'expéditeur dans le nom du fichier peut prêter à confusion je pense, dans le sens où nous ne sommes pas toujours arrivé à lire le nom propre (voir pull request  #16 ).

**Comment by axellelecroq** [comment]
En effet @HugoSchtr, du coup tu proposerais juste : `collection_typededoc_ndefolio` c'est-à-dire, pour reprendre l'exemple : `dp_lettre_ff192`

Par ailleurs, quand on regarde dans nos dossier, c'est rangé pas ordre alphabétique et ce n'est pas facile de rechercher un document dans le dossier de presse par exemple. Il serait peut-être plus judicieux de mettre le numéro de folio à la suite de la collection, puis terminer par le type de document, comme par exemple: `f192_dp_lettre` afin que les folios soient rangés dans l'ordre de la numérisation gallica. Qu'en pensez-vous ? Et si jamais on regroupe tout notre corpus dans un seul et même dossier, au moins les textes de chaque collection seront rangés à la suite des uns et des autres.

**Comment by HugoSchtr** [comment]
@axellelecroq Je pense même qu'on peut s'en tenir au simple : ```collection_ndefolio```
Je ne pense que cela soit nécessaire d'indiquer si c'est un article ou une lettre dans le nom du fichier. 

Je pense qu'il est préférable, de commencer par ```collection_ndefolio```. Si on garde la structure que nous avons actuellement, c'est-à-dire dans différents dossiers, tout est déjà clair. Si on rassemble tout dans un gros dossier corpus, sans sous-dossiers, on aura ainsi, par exemple : 

* dp_f1
* dp_f2
* pm_f1
* pm_f2
* pp_f1
* pp_f2

Ainsi on voit directement le nom de la collection premier.

> Pour reprendre la remarque de @ArsGeo pour laquelle je suis entièment d'accord, il faudrait donc que tous les folios encodés/transcrits dans un même document apparaissent dans le nom du fichier. Par exemple : `f192-f193-f194_dp_lettre` non ? Comme ça si on a un doute à propos d'un oubli de document, on a juste à faire une recherche du numéro de folio dans nos dossiers.

J'ai ouvert une issue ( #21) pour discuter de la structure, je propose qu'on transfère ce début de discussions là-bas. 👍
