### ISSUE TITLE
Structure du corpus

### ISSUE THREAD

**Issue by HugoSchtr** [axellelecroq/apollinaire-project#21]
J'ouvre cette issue pour que l'on puisse discuter de la structure de nos fichiers corpus .txt, et donc par conséquent les fichiers qui seront encodés. 

J'ai en effet remarqué dans le dossier de presse que l'on a eu deux méthodologies pour la création de fichier : 
* Rassembler dans un seul fichier .txt un article ou une lettre qui s'étale sur plusieurs folios. Donc une structure située au niveau de la lecture du document.
* Un folio = un fichier .txt. Donc une structure qui reprend celle du document papier sur Gallica, à son état matériel j'entends, comme une "copie" en texte sur github. 

La première méthodologie implique d'emblée une compréhension du texte, tandis que la deuxième méthodologie présente des données brutes.

On peut tout à fait adopter une structure pour le corpus, et une autre pour l'encodage je pense. J'aurais tendance à préférer la deuxième méthodologie pour le corpus, pour présenter des données non-interprétées, et la première pour l'encodage sachant qu'on entre dans l'interprétation de notre corpus par le biais de l'encodage.

Qu'en pensez-vous ? 

En vous souhaitant un bon dimanche !

**Comment by Juliettejns** [comment]
J'aurais aussi tendance à dire qu'il serait plus logique de présenter les données brutes et sans interprétation pour nos fichiers corpus. Surtout que si on les réorganise maintenant, on risque forcément de les interpréter à la lumière de notre travail d'encodage! Je suis donc plutôt pour la deuxième méthode également.

**Comment by axellelecroq** [comment]
Personnellement, je ne trouve pas que ça a une grande importance pour les fichiers .txt Il est vrai que c'est bien d'avoir un nommage homogène mais je pense que pour les fichiers .txt c'est un peu trop tard. Nous pouvons cependant nous poser la question sur les fichiers d'encodage car c'est sur quoi nous travaillons maintenant. 
Par contre, si il faut renommer tous les fichiers .txt, techniquement cela signifie supprimer l'ancienne version du fichier pour en placer une nouvelle, donc un nouveau fichier.  En tout cas, si tout le monde est d'accord pour renommer tous les fichiers .txt, tout le monde doit le faire et pas une seule personne désignée afin de garder la trace des personnes ayant travaillé dessus.

**Comment by leaprs** [comment]
Je partage l'avis d' @axellelecroq sur le fait de laisser les documents en l'état pour les fichiers .txt et de nous concentrer sur les dossiers .xml. Pour ma part, je trouve plus aisé de se retrouver dans des documents qui s'appuient déjà une structure conceptuelle du document. 
Donc je suis tout à fait d'accord avec toi @HugoSchtr pour rester sur un niveau conceptuel pour le nommage des fichiers .xml en suivant le modèle, pour le cas des lettres, par exemple : un fichier .xml = une lettre.

**Comment by axellelecroq** [comment]
Est-ce que lúne de ces propositions réfléchies sur Discord conviendrait ?

-  `185-186-187_lettre` --> tous les folios sont indiqués
-  `185-187_lettre` --> l'intervalle des folios est indique
-  `201_articles` --> pour un folio composé d'articles

À savoir que nous prendrons une structure différente pour les `xml:id` car ces derniers ne peuvent commencer par un entier.

**Comment by PaulineChauvet** [comment]
Bonjour à tous,

Pour ma part, je pense que la deuxième proposition est clairement la plus pertinente: indication de l'intervalle des folios, qui reprend les bonnes pratiques méthodologiques de citation des paginations.

**Comment by axellelecroq** [comment]
Est-ce que cela signifirait que nous devons faire un fichier .xml pour chaque folio ?
Ou bien la deuxième option s'appliquerait seulement pour le fichier .txt ?

**Comment by PaulineChauvet** [comment]
La deuxième option s'appliquerait uniquement au fichier .txt!

**Comment by axellelecroq** [comment]
Tout le monde est-il d'accord pour renommer tous les fichiers .txt, sachant que cela implique que tout le monde le fasse et pas seulement @HugoSchtr ?

**Comment by leaprs** [comment]
@axellelecroq pour répondre à tes propositions : pour moi, c'est la première que je trouve très explicite à savoir indiquer chaque folio mais si les intervalles conviennent à tous, pas de soucis :)
On va dire que ça m'aide à acter si je me suis bien occupée de tel folio et dans la mesure où souvent ça ne dépasse pas 3 folios, les noms de fichier restent d'une "longueur" acceptable.

**Comment by Juliettejns** [comment]
Je suis d'accord avec tes propositions @axellelecroq. Je préfère également la deuxième solution de nommage, avec les intervalles, puisque cela reste assez compréhensible et concis. La même méthode serait appliquée pour les poèmes? Si oui, peut être faudrait-il rassembler le poème _À la santé_, qui est divisé en feuillets dans un dossier, avant de renommer les fichiers?

**Comment by Juliettejns** [comment]
Je suis également d'accord avec tes propositions @axellelecroq. La deuxième méthode de renommage, avec les intervalles, me semble la plus concise, tout en restant compréhensible même si je comprends ta position, Léa.

**Comment by D0riane** [comment]
Bonsoir, 
je dois avouer avoir du mal à comprendre si l'on parle des fichiers txt ou des fichiers xml..?
**Fichier txt :** Pour ma part, comme @axellelecroq , je ne suis pas pour renommer les fichier txt, puisque nous avons finis de les traités et que les noms étaient alors suffisamment explicites pour qu'on y arrive. Cependant, si la majorité veut renommer les fichiers txt, bien entendu, je me joindrais à l'effort commun. 
**Fichier xml :** Je suis plutôt pour l'intervalle (qui sous entend que les folios intermédiaires ont été traité) car nous avons un article sur 5 folios... Ca commence à faire un nom de fichier un peu long.

**Comment by leaprs** [comment]
Il me semble que Doriane a résumé la situation. 
Je comprends tout à fait pour les noms de fichiers long (je ne savais pas que ça allait jusqu'à 5 folios) donc ok pour l'intervalle dans les fichiers xml !

**Comment by ArsGeo** [comment]
De même pour les poèmes, qui eux sont très longs !

**Comment by HugoSchtr** [comment]
Idem, je suis pour utiliser les intervalles ! 

Par contre, pour les .xml, je pensais que nous avions décidé de rassembler tous les encodages dans un seul fichier, non ? Ou alors là on parle de l'étape intermédiaire où nous allons poster nos fichiers xml d'encodage en vue de constituer le gros fichier final ? 

Pour les .txt, il semblerait qu'on se dirige pour les laisser en l'état. Cette issue avait surtout pour but de discuter de comment allons nous présenter le corpus .txt, et s'il est nécessaire ou non de le présenter d'une manière normalisée pour que les transcriptions puissent être réutilisées en dehors de ce projet par d'autres. Du coup si personne ne s'y oppose, j'irai renommer ceux que j'ai posté par erreur sous le nom d'article mais qui sont en fait des lettres pourchiers .txt c'est un peu trop tard. lever l'ambiguïté que j'ai généré. Deux je crois, enfin pas beaucoup. Je ferai une branche qui part de main, puis une PR pour vous notifier des changements histoire de voir les fichiers renommés ! :)

**Comment by HugoSchtr** [comment]
Idem, je suis pour utiliser les intervalles, j'ai un exemple d'article de presse en tête qui s'étale sur pas mal de folios, ça ferait un nom trop long. 

Par contre, pour les .xml, je pensais que nous avions décidé de rassembler tous les encodages dans un seul fichier, non ? Ou alors là on parle de l'étape intermédiaire où nous allons poster nos fichiers xml d'encodage en vue de constituer le gros fichier final ? 

Pour les .txt, il semblerait qu'on se dirige pour les laisser en l'état. Cette issue avait surtout pour but de discuter de comment allons nous présenter le corpus .txt, et s'il est nécessaire ou non de le présenter d'une manière normalisée pour que les transcriptions puissent être réutilisées en dehors de ce projet par d'autres. Du coup si personne ne s'y oppose, j'irai renommer ceux que j'ai posté par erreur sous le nom d'article mais qui sont en fait des lettres pour lever l'ambiguïté que j'ai généré. Deux je crois, enfin pas beaucoup. Je ferai une branche qui part de main, puis une PR pour vous notifier des changements histoire de voir les fichiers renommés ! :)
