### ISSUE TITLE
Annotation numéro de page

### ISSUE THREAD

**Issue by axellelecroq** [axellelecroq/apollinaire-project#26]
Bonjour à tous,

lors de la transcription vous avez tous du remarquer qu'un numéro de page a été rajouté en haut à droite des documents. 
Par exemple ici : https://gallica.bnf.fr/ark:/12148/btv1b525088021/f196.item on y trouve le numéro 81.
Qu'est-ce qu'on fait avec ce numéro ? est-ce pertinent de le faire apparaître dans notre encodage ou seul le numéro de folio est suffisant ?
Par exemple avec cette balise qui permettrait d'indiquer directement le numéro du folio gallica mais pas le numéro de page rajouter en haut à droite.  

`<div type="recto" n="196" facs="https://gallica.bnf.fr/ark:/12148/btv1b525088021/f196.item">`

**Comment by D0riane** [comment]
Bonjour, 
Je me suis également posée cette question. Existe-t-il une balise permettant de signaler une ancienne pagination? 
A défaut de trouver mieux je l'ai signalé comme ça (par exemple):
<note type="ancienne_pagination"><num rend="barré">24</num><num>83</num></note>.
Je trouvais intéressant de le signaler pour l'"histoire" de notre document et décrire sa matérialité dans son ensemble. Est ce que cela permettrait de proposer un encodage qui donnerait la possibilité à terme de reconstituer d'anciens ensemble de documents par exemple ? On peut revenir dessus si cela n'a selon vous aucun intérêt.

**Comment by D0riane** [comment]
Correction de mon commentaire précédent : 

A défaut de trouver mieux je l'ai signalé comme ça (par exemple):
`<note type="ancienne_pagination"><num rend="barré">24</num><num>83</num></note>`

**Comment by Juliettejns** [comment]
Bonjour! 

Je suis d'accord avec Doriane, je trouve ça intéressant d'encoder cette pagination.

Ta proposition d'encodage me convient tout à fait, personnellement. Ne serait-il pas également possible d'indiquer si il s'agit d'une pagination réalisée par un bibliothécaire, et non par Apollinaire? Je pense par exemple à un attribut @hand.

Qu'en pensez-vous?

**Comment by HugoSchtr** [comment]
Entièrement d'accord avec vous. @hand proposé par @Juliettejns est effectivement bien pratique pour ce cas ! 

Cependant, avons-nous moyen de trouver qui est à l'origine de la pagination ? Devons-nous par exemple partir du principe que la rature diagonale a été effectuée par une personne passée après Apollinaire, ou bien devons-nous supposer qu'Apollinaire est à l'origine de toutes ces annotations ?

**Comment by leaprs** [comment]
D'accord avec la proposition de Doriane ! 
Dans la même logique que Hugo, je me demande quelle valeur peut prendre @hand. 
Est-ce que cela conviendrait à tout le monde ?
```<note type="ancienne_pagination" hand="librarian"><num rend="barré">24</num><num>83</num></note>```

**Comment by axellelecroq** [comment]
Est-il intéressant d'indiquer où il se trouve physiquement dans la page, notamment par l'attribut @rend dans la balise `note`.
Par exemple: 
`<note type="ancienne_pagination" hand="librarian" rend="top_right"><num rend="barré">24</num><num>83</num></note>`

**Comment by D0riane** [comment]
Je suis d'accord avec toutes vos propositions : `@hand="librarian"` et le signalement de l'emplacement sur la page avec `@rend` et l'utilisation de parenthèses pour les précisions de la valeur. Je suis donc pour l'appliquer à notre encodage.

**Comment by axellelecroq** [comment]
Nous sommes majoritairement d'accord apparement, nous pouvons donc appliquer l'exemple indiqué plus haut dans nos encodages.
Je clos cette PR.

**Comment by axellelecroq** [comment]
Il a été décidé lors du visio du 12 février de ne plus encoder cette numérotation du libraire pour des raisons structurelles d'encodage. 
Le CR de cette réunion est disponible [ici](https://github.com/axellelecroq/apollinaire-project/blob/main/cr_reunions/visio_12-2_groupe-dp.md).
