### ISSUE TITLE
Tampon bibliothèque (dossier de presse)

### ISSUE THREAD

**Issue by leaprs** [axellelecroq/apollinaire-project#27]
Bonjour à tous, 

De nombreux tampons (de bibliothèques ?) sont imprimés en rouge sur les pages du dossier de presse.
Exemple : https://gallica.bnf.fr/ark:/12148/btv1b525088021/f177.item.r=Apollinaire%20manuscrits.zoom 
Je propose cette ligne de code pour son encodage : 
```<span type="library_stamp" rend="red"/> ```

Pensez-vous qu'il est judicieux de les inscrire dans l'encodage dans la mesure où il est impossible de lire les inscriptions qu'il contient ?

**Comment by D0riane** [comment]
Bonjour, 
Il me semble que pour les articles de presse (et donc les lettres?), il s'agit toujours de la même estampille. La base Bibale de l'IRHT renseigne un certain nombre des estampilles de bibliothèque, je peux y jeter un oeil pour essayer de trouver l'estampille utilisée à chaque fois, permettant une description un peu plus précise pour le msDesc <stamp>. Si les différentes estampilles sont signalées dans le MsDesc, il ne sera peut être pas nécessaire de l'ajouter dans l'encodage de chacun des articles ?

**Comment by axellelecroq** [comment]
Je suis d'accord avec @D0riane.
Ce serait en effet une alternative bien meilleure de l'enregistrer directement au sein du msDesc et non dans l'encodage lui-même. 
Si les tampons sont d'ailleurs différents, peut-être serait-il judicieux de les indexer tous, d'une manière ou d'une autre (msDesc par exemple) avec un ID notamment auquel on réfère dans l'encodage?

**Comment by D0riane** [comment]
Je n'étais pas certaine de la possibilité d'ajouter un xml:id pour les <stamp> mais si tel est le cas, ça me semble une très bonne option !

**Comment by D0riane** [comment]
Je pense qu'il s'agit de cette estampille : http://bibale.irht.cnrs.fr/44365 . Utilisée à la BnF, département des archives et manuscrits après 1870. Nous pourrons donc compléter le msDesc grâce aux informations fournies à ce lien.

**Comment by leaprs** [comment]
Merci Doriane, super bon plan cette base de données ! Je suis d'accord également pour mettre cette information dans le msDesc

**Comment by axellelecroq** [comment]
On l'enregistre dans le `<msDesc>`  mais qu'est ce qu'on note dans l'encodage de la lettre pour signifier le tampon du coup ?
Je trouve qu'il n'est pas nécessaire de l'indiquer si il est présent sur toutes les pages et si il y en a qu'un seul. 

Par contre, si il y en a plusieurs ou bien si toutes les pages de sont pas tamponées, serait-il pas important d'indiquer dans l'encodage la présence de tel ou tel tampon sur la page encodée ?

**Comment by D0riane** [comment]
Après avoir passé en revu les pages concernés par l'encodage du dossier de presse (article+lettre), j'ai l'impression qu'il n'y a que cette estampille de bibliothèque. Elle n'est pas présente sur toute les pages, mais quasiment une fois par article ou lettre. 

J'aurais tendance à proposer de l'encoder une seule fois dans le `<msDesc>` et à préciser par exemple dans `<stamp>`: 
`<note>Utilisation quasi-systématique de cette estampille sur les pages du document.</note>` .
J'ai l'impression que les estampilles ont été apposées en une fois avec le même tampon, surement quand le document entier est entré à la BnF. Je ne pense pas donc qu'il y ait grand chose à tirer de la présence et de la position de l'estampille sur une page et pas une autre. (geste un peu automatique du bibliothécaire?). 

Un autre tampon est présent dans un article, il s'agit du tampon de la Poste de Poitier qui sera donc à encoder différemment.

**Comment by axellelecroq** [comment]
Je suis d'accord avec ta proposition @D0riane !
Nous avons aussi eu des tampons de la poste dans les lettres que nous avons directement encodés au sein de la lettre.

**Comment by HugoSchtr** [comment]
L'estampille ne m'était pas du tout passée par la tête ! Merci pour vos échanges, c'est super intéressant à lire pour ma part !
Et du coup je vous suis totalement dans l'intégration de l'estampille dans le ```<msDesc>``` et je suis d'accord avec la proposition de @D0riane !

**Comment by leaprs** [comment]
D'accord également avec la proposition de @D0riane  !
