### ISSUE TITLE
Proposition d'encodage du contexte épistolaire_Element CorrespDesc

### ISSUE THREAD

**Issue by PaulineChauvet** [axellelecroq/apollinaire-project#28]
Bonjour à tous,

Afin de restituer les éléments de contexte épistolaire nécessaires à l'édition numérique des lettres du dossier de presse, que pensez-vous d'affiner un peu notre granularité d'encodage en utilisant l'élément "correspDesc" ainsi que ses éléments enfants "correspAction" et "correspContext"?

Voici un exemple: 
![Exemple_CorrespDesc](https://user-images.githubusercontent.com/74914886/106786958-694c7500-664f-11eb-9cad-565c0a58feda.jpg)

L'élément "note" est peut-être superflu mais je pense que la structuration des données élémentaires des épistoliers et de leur contexte d'écriture est importante.

Merci d'avance pour votre avis!

**Comment by leaprs** [comment]
Après un petit tour sur les TEI guidelines, il me semble que l'élément <correspDesc> et ses enfants (https://tei-c.org/release/doc/tei-p5-doc/en/html//HD.html#HD44CD) correspondraient davantage à un dossier de lettres où l'on suit des échanges entre personnes identifiées avec un contexte détaillé.
Comme ici, il s'agit d'un dossier de presse rassemblant des lettres éparpillées (dont la signature est parfois illisible et sans réponse du principal intéressé), je ne pense pas qu'il s'agisse à proprement d'une correspondance de même nature que ton exemple. À voir avec ce qu'en pense les autres :)

**Comment by axellelecroq** [comment]
Je suis assez d'accord avec @leaprs. Il n'y a pas tellement de contexte de correspondance. Il s'agit d'une seule lettre reçue pour laquelle nous n'avons pas la réponse.
Aussi, je pense que ce serait assez incompatible avec le fait d'avoir une ODD commune pour tout le dossier de presse. 
Pour moi, cette PR peut être fermée.

**Comment by HugoSchtr** [comment]
Il est vrai qu'en l'absence de recherches plus poussées sur le recueil, j'ai peur que nous n'arrivions pas à pouvoir atteindre ce niveau de granularité !

**Comment by leaprs** [comment]
Si tout le monde est d'accord, je propose qu'on ferme cette issue ?

**Comment by PaulineChauvet** [comment]
C'est d'accord pour moi!

**Comment by HugoSchtr** [comment]
okay pour moi aussi!
