### ISSUE TITLE
Structuration encodage dossier de presse

### ISSUE THREAD

**Issue by D0riane** [axellelecroq/apollinaire-project#33]
Bonjour à tous, 
En vue de fusionner à terme les encodages des articles et des lettres, il m'a semblé important d'échanger sur la manière dont nous avions structuré globalement l'encodage des article. 
Pour les articles, avec @HugoSchtr , nous avons choisi d'imbriquer deux `<div>`, l'une qui représente la page et l'autre qui représente l'article. Cela permettait de prendre en compte l'aspect matériel de ce dossier de presse, notamment en signalant ainsi lorsque plusieurs articles étaient collé sur une même page. Par ailleurs, l'utilisation du xml:id pour l'article permettait de faire référence à un même article lorsque celui-ci est sur plusieurs pages.   

Qu'en pensez vous ? Cela serait il adapté pour les lettres également ou comment pourrait on le modifier pour que cela soit plus pertinent ? 

Exemple : 
<text>

      <body>

         <div type="page" n="n° de folio">

        <pb n="n° de folio" facs="URL vers numérisation de la page"/>

        <note/> 
        

            <div type="article" xml:id="article1-f201" xml:lang="norme iso langue">
            

            </div>
       </div>
      </body>
</text>

**Comment by axellelecroq** [comment]
Nous avons utilisé la même structure dans nos encodages, justement en vue de la mise en commun des lettres et des articles.
Nous avons utilisé cette structure: 
`         <div type="letter">
            <div type="recto" n="192" facs="https://gallica.bnf.fr/ark:/12148/btv1b525088021/f192.item">
              [encodage recto]
            </div>
            <div type="verso" n="193" facs="https://gallica.bnf.fr/ark:/12148/btv1b525088021/f193.item">
               [encodage verso]
            </div>
         </div>`

C'est la même structure que la votre, mais nous avons inversé le type de document que nous avons mis en premier.
Cela fait sens dans notre cas, car c'est une lettre qui est divisé en plusieurs pages. Alors que dans votre cas, c'est une page qui est divisée en plusieurs articles.
Afin que les deux encodages puissent être compatibles, serait-il peut-être possible dans votre cas, de rajouter une balise `<div>` supérieur avec un attribut @type ayant pour valeur "page articles" ou quelque chose comme ça ?
`<div type="page_article">`
Cela serait le pendant de notre `<div type="letter">`.

Nous pouvons aussi utilisé l'attribut @subtype. Je l'ai utilisé notamment pour encoder une lettre écrite sur une carte de visite. Voici donc mon exemple : `<div type="letter" subtype="visitcard">`
Mais peut-être que nous pouvons utiliser cet élément pour indiquer s'il s'agit de lettre ou d'article : `<div type="dossierdepresse" subtype="letter">`.

**Comment by HugoSchtr** [comment]
Mélanger deux structures de div ne risquerait-il pas d'engendrer de la confusion si nous rassemblons tout au sein d'un seul fichier XML ? 

@D0riane, j'aurais envie de te proposer d'adopter la structure d'@axellelecroq et @leaprs, ça marche pour les articles de presse qui sont divisés en plusieurs pages. Cependant, j'ai peur que ça ne corresponde pas aux folios avec plusieurs articles, car pouvant amener de la redondance.

J'imagine que ça donnerait ça : 

```
    <div type="article" xml:id="article1-f201">
        <div n="num du folio" facs="url vers numérisation">
             [encodage]
        </div>
     </div>
    <div type="article" xml:id="article2-f201">
        <div n="num du folio" facs="url vers numérisation">
             [encodage]
        </div>
     </div>
```

Ou alors, peut-être faudrait-il casser la structure du document. Considérer que les lettres sont un ensemble, et les articles un autre, et qu'ils nécessitent donc un encodage différent. Mais si on veut rester cohérent on va certainement devoir adopter une seule structure de div, non ? 

J'aime bien @subtype sinon ! Je pense que ça marche bien pour l'intégralité du corpus si on fait des div par gros ensembles comme tu l'as montré dans ton tout dernier exemple @axellelecroq.

**Comment by HugoSchtr** [comment]
(Je profite de cette issue pour clarifier un peu notre ODD : toujours selon l'idée de garder la structure du document source dans l'encodage, @D0riane et moi avons utilisé des ```<pb>``` et des ```<lb/>```. Je vois que c'est pareil de votre côté donc je propose qu'on reste dans cette direction. :) )

**Comment by leaprs** [comment]
Je ne suis pas certaine de @subtype car je trouve qu'on perd en lisibilité "immédiate" (si j'ose dire) et que @type avec comme valeur "dossier de presse" est redondant comme le teiHeader se chargera déjà d'indiquer la nature du document. 

Pour ma part, je pense que comme @HugoSchtr  l'a mentionné, le mieux serait de mélanger deux div avec @type soit article ou soit lettre. Pour ce qui est de la redondance pour les folios avec plusieurs articles, peut-être déplacer le xml:id sur la seconde div (celle qui contient @n et @facs), je ne sais pas si cela serait possible en l'état ?

**Comment by D0riane** [comment]
Je suis assez d'accord avec @leaprs , je pense qu'un `@type ` dossier de presse ne soit pas nécessaire puisque nous encodons que le dossier de presse dans ce document / avec cette ODD, autant passer directement lettre ou article en `@type`. 

Je ne suis pas (encore) ultra convaincue de l'imbrication des balises `<div>` dans cet ordre pour les articles, surtout à cause du cas de plusieurs articles par pages. Si on trouve un `@type`approprié pour la deuxième `<div>`, cela pourrait expliciter notre démarche et préciser ce que nous encodons dans cette `<div>`, non ? Effectivement, c'est assez évident quand il n'y qu'une lettre / article par page, mais ça ne l'est pas vraiment pour les articles sur plusieurs pages et plusieurs articles sur une page. Complété avec les `@n`et `@facs`, ça me semble éclaircir la situation. 
Je pense par contre, qu'il faut laisser le xml:id sur la première balise `<div>`, puisqu'on y identifie l'article.

**Comment by D0riane** [comment]
Je sais qu'on en avait parlé @HugoSchtr, mais ma réflexion me ramène toujours à ça : pourquoi ne pas utiliser un `<pb>`+ `@attributs_qui_concerne_la_page` pour signaler les changement de pages plutôt qu'une deuxième `<div>`..?

**Comment by HugoSchtr** [comment]
@D0riane Effectivement, une ```<div``` unique accompagnée d'un ```<pb>``` réglerait le problème ! :) La ```<div>``` symboliserait donc l'article, est-ce exact ?

**Comment by axellelecroq** [comment]
Peut-être existe-t-il une balise dans le style de `<pb>` ou `<cb>` que nous pourrions utiliser pour désigner différents articles sur une même page ?

**Comment by HugoSchtr** [comment]
Je viens de trouver la balise générique ```<milestone>``` qu'il nous suffirait d'habiller avec des attributs pour compléter le ```<pb>```. La balise permet dans les grandes lignes de définir un point de séparation entre différentes sections. Dans la doc y a marqué "marque un point permettant de délimiter les sections d'un texte selon un autre système que les éléments de structure." Pensez-vous que nous devons comprendre au sein d'un même texte ? Et donc non pour délimiter plusieurs textes ?
 Voir la [documentation.](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#CORS5) Et pour la balise en particulier : [ici](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-milestone.html).

**Comment by axellelecroq** [comment]
La balise `<milestone>` semble en effet super adaptée !

**Comment by HugoSchtr** [comment]
Du coup avec les autres issues je me retrouve un peu perdu pour la structure de div qu'on adopte pour le dossier de presse. :( 
On part sur quoi ?

**Comment by leaprs** [comment]
Suite à la réunion de ce matin, la structure du dossier de presse choisie est la suivante : 
```
<div type=”article/lettre” n="numero_folios" xml:id="" xml:lang="">
      <pb type="verso/recto" subtype="empty/copy" facs="lien_vers_Gallica"> → lettres
      <pb facs="lien_vers_Gallica"> → articles
</div>
```
Ainsi, l'élément ```<div>``` correspond à la conceptualisation du dossier de presse et l'élément ```<pb>``` renvoie principalement à son intégrité physique et également, à des compléments sémantiques pour les lettres.

**Comment by axellelecroq** [comment]
[le lien du compte-rendu de la réunion](https://github.com/axellelecroq/apollinaire-project/blob/main/cr_reunions/visio_12-2_groupe-dp.md). 
Cette issue peut être fermée, d'après moi.
