### ISSUE TITLE
Encodage des folios de type copie ou vide - dossier de presse

### ISSUE THREAD

**Issue by leaprs** [axellelecroq/apollinaire-project#34]
Bonsoir à tous ! 

J'en profite à la suite de l'issue de @D0riane sur la structuration textuelle pour évoquer le cas des pages blanches ou copies qui sont plutôt nombreuses dans le dossier de presse. Je suis partie du principe qu'il faudrait trouver un moyen de les signaler en renvoyer vers son @facs pour ainsi montrer au lecteur qu'il ne s'agit pas d'un oubli de notre part mais d'une situation particulière dans le dossier de presse.

En parcourant les guidelines, je n'ai pas trouvé grand chose sur un quelconque élément ou attribut permettant d'indiquer ce genre de non-contenu (il y a bien un élément <empty> mais pour l'ODD). Pensez-vous que l'encodage de ces parties soit pertinent ? Si oui, avez-vous des idées ou connaissance d'un élément particulier qui m'aurait échappé ?

Faute de mieux et considérant que div ne peut être auto-fermante, on pourrait opter par la rédaction d'un commentaire du type : 

```
<div type="recto" n="194" facs="https://gallica.bnf.fr/ark:/12148/btv1b525088021/f194.item.r=Apollinaire%20manuscrits.zoom">
       [encodage]
</div>
<div type="verso" n="195" facs="https://gallica.bnf.fr/ark:/12148/btv1b525088021/f195.item.r=Apollinaire%20manuscrits">
       <!-- La page est vide -->      
</div>
```

**Comment by D0riane** [comment]
Bonjour ! Nous n'avons pas rencontré ce cas dans les articles, je n'avais donc pas réfléchit à un encodage jusqu'alors. J'ai regardé un peu les TEI guidelines en vain. J'avais tendance à dire de ne pas l'encoder tout simplement, mais c'est vrai que l'ajout d'un `@facs` est intéressant donc ton idée me semble bien. Une `<div>` peut elle être vide ?

**Comment by leaprs** [comment]
@D0riane de ce que je me souviens de mes transcriptions d'articles, en effet il n'y avait pas de page vide mais parfois entre folios, on avait des sortes de copies : par exemple, un folio présentait les cartes articles collés sur une page et les folios suivant sont en fait des zooms de chaque article de ce même folio. Les premiers articles du dossier fonctionne ainsi : https://gallica.bnf.fr/ark:/12148/btv1b525088021/f146.item.r=Apollinaire%20manuscrits 

Après comme tu le dis, effectivement c'est plus du détails pour les articles et peut-être avez vous déjà trouvé quelque chose pour signifier cela. 

Je ne crois pas qu'une ``` <div> ``` peut rester vide comme elle indique une structure à venir, je l'ai pas trouvé explicitement dans les guidelines mais du fait qu'elle ne peut être auto-fermante, cela induirait qu'il y ait forcément un contenu à l'intérieur - d'où mes commentaires un peu léger mais faute de mieux...

**Comment by axellelecroq** [comment]
Je pense que le choix de la balise afin de manifester une page vide va dépendre des cas. Je trouve ta proposition @leaprs intéressante si il s'agit d'une page vide complète entre deux folios.

Dans le seul cas où j'ai rencontré le problème de la page vide, il s'agissait d'une la page de gauche d'une copie double, et la page de droite était écrite. Les deux pages de la copie double étaient numérisée dans la même vue.

![double-page-apollinaire](https://user-images.githubusercontent.com/60888306/107374530-faa46700-6ae7-11eb-9b08-30be366e5867.jpg)

Voici ma proposition d'encodage pour cette page pour exemple : 
`<div type="verso" n="181"
               facs="https://gallica.bnf.fr/ark:/12148/btv1b525088021/f181.item.r=Apollinaire%20manuscrits">
               <note type="ancienne_pagination" hand="librarian" rend="align(top right)"
                  ><num>76</num></note>
               <pb n="1"/> 
               <pb n="2"/>
               <p>prolongent si haut leurs <lb/>perspectives. Et puis, <lb/>la parfaite série des
                  <lb/>souvenirs de prison ! Tout <lb/>cela m'a charmé, et <lb/>je vous admire.</p>
               <closer>
                  <salute rend="align(center)">Bien à vous</salute>
                  <signed rend="align(center)">Bounélier</signed>
               </closer>
            </div>`

J'ai donc utilisé la balise `<pb>` et non une `<div>`. Aussi, je ne sais pas si c'est ça sert à quelque chose d'ouvrir une div juste pour y mettre un commentaire. Je pense qu'il vaut mieux se diriger vers une balise autofermante mais à part `<pb>` c'est vrai que je n'en ai pas d'autres en tête et je n'ai pas cherché dans toute la documentation. 

Une possibilité serait aussi de les laisser de côté et de ne pas les faire apparaître dans l'encodage.

**Comment by HugoSchtr** [comment]
``<pb>``` me semble très bien pour décrire une page vide ! Selon la [doc](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-pb.html) de la balise, on peut fournir un attribut @type. On pourrait l'utiliser et lui attribuer une valeur "blank", "empty" ou "vide", je sais pas. 
On peut mettre un commentaire pour préciser la chose, mais si on imagine une lecture de l'encodage par une machine, ou une transformation XSLT, etc., un attribut permettrait de mieux faire le tri et d'accéder à l'information facilement. 
Un ```<pb/>``` sans @type indiquerait une page avec du texte, tandis qu'un ```<pb type="empty">``` indiquerait une page vide.

**Comment by leaprs** [comment]
En fait, l'intérêt d'une ```<div>``` était l'utilisation des attributs @facs et @n. Effectivement dans ton exemple @axellelecroq, comme tu fais référence à un même folio, ```<pb>``` peut endosser cette tâche car le folio est bien identifié au préalable dans ta ```div```. Dans mon cas, l'idée était justement de mentionner quand même l'existence du folio même complètement vide.

L'utilisation de  ```pb``` dans ce cas très précis et si l'on sauvegarde notre structure une ```div``` = une folio,  donnerait quelque chose comme ça : 
```<div type="recto" n="194" facs="https://gallica.bnf.fr/ark:/12148/btv1b525088021/f194.item.r=Apollinaire%20manuscrits.zoom">
       <pb/>
       [encodage]
</div>
<div type="verso" n="195" facs="https://gallica.bnf.fr/ark:/12148/btv1b525088021/f195.item.r=Apollinaire%20manuscrits">
     <pb type="empty"/>   
</div>```

Qu'en pensez-vous ?

**Comment by HugoSchtr** [comment]
ça me convient complètement :)

**Comment by axellelecroq** [comment]
Résolu lors du visio du 12 février, le [CR est disponible sur le repository](https://github.com/axellelecroq/apollinaire-project/blob/main/cr_reunions/visio_12-2_groupe-dp.md).
Il s'agira d'indiquer une feuille vide dans l'attribut `@subtype` d'une balise `<pb>`.
