### ISSUE TITLE
Encodage des éléments figurés dans les poèmes manuscrits

### ISSUE THREAD

**Issue by Juliettejns** [axellelecroq/apollinaire-project#35]
Bonsoir à tous!

Suite à la discussion ouverte sur la PR #30, j'ouvre cette issue afin de discuter de l'encodage des figures présentes dans de nombreux poèmes manuscrits, par exemple, sur le feuillet 25 (https://gallica.bnf.fr/ark:/12148/btv1b52505641f/f25):

![gribouilli1](https://user-images.githubusercontent.com/56683417/107407717-4c5de900-6b0a-11eb-8bbb-680f3b4d0806.png)
![gribouilli2](https://user-images.githubusercontent.com/56683417/107407784-61d31300-6b0a-11eb-9d6a-ebfd0cfef532.png)

Comme préconisé par Pauline, la balise figure me semble la plus utile. Cependant, je pense qu'il serait intéressant de trouver un moyen de normaliser l'encodage de ces éléments. D'après les teiguidelines (https://www.tei-c.org/release/doc/tei-p5-doc/fr/html/ref-figure.html), ce genre d'encodage peut être réalisé de cette façon:
```

`<figure>`
 <head>La tour rouge, de Giorgio De Chirico</head>
 <figDesc>Le tableau représente un donjon au pied duquel s'étend un espace quasiment vide,
   hormis quelques détails</figDesc>
 <graphic url="http://www.cineclubdecaen.com/cinepho/peint/dechericho/tourrouge.jpg"
  scale="0.5"/>
</figure>
```
Il me semble qu'il n'est pas possible de dire autant de choses sur des éléments aussi restreints. Je propose donc de réaliser uniquement un encodage tel que:
`<figure place="emplacement de l'image" rend="description réduite"/>`
Cela me semble cependant assez réduit.

Qu'en pensez-vous?

**Comment by axellelecroq** [comment]
Je suis d'accord avec tes propositions. Je n'ai pas en tête toutes les "gribouillis" qu'il y a dans les documents.
 Je trouve cependant intéressant les décrire quand toutefois il s'agit d'éléments reconnaissables. Mais pour le reste, notamment comme pour l'exemple que tu as montré, j'en resterais à un encodage simple, tel que tu le proposes, et qui a le mérite de ne pas ignorer ces éléments manuscrits.

**Comment by PaulineChauvet** [comment]
Je suis également d'accord avec vos propositions. Nous pouvons en rester à l'exemple que tu proposes pour des esquisses ou des dessins se prêtant peu à une description fine, mais faire usage d'un "figDesc" lorsque l'élément figuré est particulièrement riche et/ou abouti.

**Comment by HugoSchtr** [comment]
D'accord pour garder ```<figDesc>``` ! Mais du coup, je pense qu'il faudrait garder la structure proposée par les teiguidelines. 

En passant, si vous avez besoin d'aide pour encoder ces petits dessins et que ça vous prend du temps à côté de l'encodage du poème, n'hésitez pas à m'assigner pour les encoder, cela ne me dérange pas du tout !

**Comment by leaprs** [comment]
D'accord avec ta proposition d'encodage @Juliettejns et merci pour l'ouverture de cette issue qui fait écho à une figure rencontrée dans le dossier de presse. 
La voici sur le folio 190 (https://gallica.bnf.fr/ark:/12148/btv1b525088021/f190.item.r=Apollinaire%20manuscrits) : 
![fleurs](https://user-images.githubusercontent.com/74207023/107650015-56085d80-6c7e-11eb-8fb5-bcce57fc2ea5.png)

Suivant vos remarques et les teiguidelines, cette figure pourrait être rapportée par l'élément ```<figure>``` comme ce qui suit : 
```
<figure rend="(top left)">
        <figDesc>Dessin imprimé représentant des fleurs dans un vase, accompagné des initiales "a.m."</figDesc>
</figure>
```
Qu'en pensez-vous ? (certes, c'est assez pauvre mais l'image n'est pas riche en informations)

**Comment by HugoSchtr** [comment]
Il est vrai qu'on peut se passer d'un ```<head>``` pour les dessins. Et la disparition de ```<graphic>``` est palliée par les renvois qu'on fait à la version numérisée. 

Du coup okay de mon côté pour la proposition de @leaprs ! Le @rend sur figure me semble être suffisant pour donner une indication de la position du dessin.

**Comment by ArsGeo** [comment]
La proposition de Léa me semble efficace ! Et oui comme dit Hugo, le renvoi vers le facsimilé est déjà fait dans _pb_.

**Comment by Juliettejns** [comment]
Je suis également d'accord avec la proposition de Léa! 
Juste une petite question, pourquoi un rend avec une valeur top left? J'aurais plutôt vu un attribut place pour cette valeur?

**Comment by axellelecroq** [comment]
Dans les teiguidelines, l'aligment est souvent indiqué dans @rend. 
Je pense toutefois que @leaprs a oublié de mettre align, et que généralement c'est indiqué comme suit :
`<figure rend="align(top left)">`

**Comment by leaprs** [comment]
Merci @axellelecroq ! Oui c'est un erreur de ma part, il y a bien un align

**Comment by Juliettejns** [comment]
Pour résumer ce qui a été dit, on encode une image de cette façon:
```
<figure rend="emplacement">
       <figDesc>description rapide</figDesc>
</figure>
```

où l'attribut rend prend la valeur: _align()_ avec entre parenthèses l'emplacement en anglais sous la forme d'une combinaison de: _top, center, margin, bottom_ et _left, right_

C'est bien ça? Auquel cas c'est bon pour moi.

**Comment by PaulineChauvet** [comment]
Oui, c'est bien cela Juliette. Nous pouvons en effet nous arrêter sur ce choix d'encodage pour les éléments figurés. Je pense qu'un attribut @place aurait pu aussi bien convenir mais l'usage de @rend a le mérite de normaliser les valeurs de cette attribut dans une liste restreinte pré-établie.
