### ISSUE TITLE
Détermination des attributs à utiliser pour les éléments gap et unclear_Encodage Versions Génétiques

### ISSUE THREAD

**Issue by PaulineChauvet** [axellelecroq/apollinaire-project#36]
Bonjour à tous,

Afin d'harmoniser et de systématiser l'usage des attributs inhérents aux éléments pour l'encodage des sources primaires, et sur la base de nos derniers prototypes d'encodage, je vous propose ceci:

- Pour signaler un élément illisible du texte, utilisation de l'élément "gap" avec les attributs: @reason pour indiquer l'illisibilité, @agent si la raison de l'illisibilité est dû à un dommage causé au matériau, @extent pour indiquer le nombre de caractères ou de mots supprimés.
- Pour signaler un mot, une expression ou un passage qui n'est pas transcrit avec certitude, en utilisant l'attribut @reason afin d'indiquer pourquoi il est difficile de transcrire le document; et l'attribut @extent pour indiquer le nombre de caractères ou de mots suscitant ce doute de transcription.

Dans ces deux cas de figures, l'attribut @extent permet de combiner la description de la quantité et de l'unité dans une seule chaîne de mots. Ainsi, l'usage de @extent ne doit pas être utilisé avec les attributs @quantity et @unit. Je privilégierais @extent dans le cadre de notre projet qui signale l'information souhaitée de façon plus pertinente et souple.

**Comment by axellelecroq** [comment]
Je suis d'accord sur tout ce que tu proposes pour signaler un élément illisible dans le texte.

Par contre pour signaler, un mot/expression/passage qui n'est pas transcrit avec certitude, de quelle balise s'agit-il ? De la balise `<gap>` aussi ?

**Comment by HugoSchtr** [comment]
Même question qu'Axelle de mon côté. 

Et d'accord pour normaliser les attributs que tu as proposé !

**Comment by ArsGeo** [comment]
Nous utilisons l'élément _unclear_ !

**Comment by axellelecroq** [comment]
Je pense qu'il serait aussi judicieux de se mettre d'accord sur toutes les valeurs d'attributs que nous pouvons utiliser afin que tout le corpus soit homogène. 
Je ne sais pas tellement comment pourrait-on s'y prendre, à part avec de la documentation HTML sur l'ODD.

Comme @HugoSchtr je pense que mettre un exemple au sein de cette issue serait vraiment pratique pour pouvoir s'y référer quand on ressentira le besoin.

**Comment by ArsGeo** [comment]
Pour caractériser une partie du texte illisible, étant donné que nous rendons déjà compte des aliénations d'origine humaine avec _del_, _delSpan_ ou encore subst, nous pourrions préférer l'attribut @agent, permettant de renseigner la cause extérieure de la détérioration (ce que nous cherchons à renseigner avec cet élément gap), mais ses valeurs sont un peu vagues : les guidelines proposent 
- _rubbing_ pour des dégâts provoqués par le frottement des bords de la feuille,
- _mildew_ pour des dégâts provoqués par de la moisissure sur la surface de feuille, et 
- _smoke_ pour des dégâts provoqués par de la fumée.

C'est assez délicat car parfois je confesse ne pas savoir ce qui a provoqué la détérioration, quels cas de figures avez-vous rencontré ?

**Comment by PaulineChauvet** [comment]
Alors l'élément "unclear" permet d'encoder les transcriptions incertaines car mal lisibles, en partie détruites, etc. L'élément "gap" est utilisé dans le cadre de notre corpus pour encoder les éléments illisibles en utilisant l'attribut @reason et la valeur illegible. Et c'est d'accord, nous allons vous présenter un exemple type parmi les échantillons réalisés pour que vous puissiez voir comment nous utilisons l'un et l'autre.

**Comment by ArsGeo** [comment]
Quelques exemples :

![image](https://user-images.githubusercontent.com/74502613/107652207-9f59ac80-6c80-11eb-9309-311389783bad.png)

![image](https://user-images.githubusercontent.com/74502613/107652390-d039e180-6c80-11eb-8746-20f3846b98c2.png)

L'attribut @reason de _gap_ ayant une valeur "_illegible_" est peut-être induite dans notre cas ?

**Comment by ArsGeo** [comment]
Ou bien l'élément _del_ concerne aussi bien les aliénations humaines que matérielles ?

**Comment by Juliettejns** [comment]
Je suis d'accord avec @ArsGeo, je me suis également demandée si l'attribut @reason était vraiment utile puisque tout le temps le même. 
Également une remarque à propos de l'attribut extent de gap: comme on peut le voir dans l'exemple de code donné par Arsène, sa valeur correspond parfois à uniquement un chiffre et d'autre fois à un nombre et une unité (word). Je propose de bien mettre juste une valeur sous forme de nombre pour @extent et l'unité sur unit.

**Comment by ArsGeo** [comment]
Rajouter un attribut `@unit` donc ? ce serait effectivement plus pratique pour l'ODD j'imagine.

**Comment by PaulineChauvet** [comment]
> En relisant les exemples je me suis souvenu que `<gap>` était de toute façon dans un `<del>`, mais je questionnais la pertinence de l'attribut @Reason de `<gap>` qui sera quasiment toujours "illegible" ? L'attribut @agent me semblait en tout cas plus utile pour les détériorations non-humaines.

L'élément "gap" n'est pas forcément dans un "del" non. Je l'ai parfois encodé dans un "add", ou dans un "addSpan", voire dans une simple division structurelle. Je ne pense pas que nous pouvons nous passer de cet élément ni de l'attribut @reason qui lui est presque interdépendant. Quant à "agent", il se prête effectivement plus à l'encodage des destructions du matériau d'origine non anthropique. A voir donc selon les cas.

**Comment by PaulineChauvet** [comment]
> Je suis d'accord avec @ArsGeo, je me suis également demandée si l'attribut @Reason était vraiment utile puisque tout le temps le même.
> Également une remarque à propos de l'attribut extent de gap: comme on peut le voir dans l'exemple de code donné par Arsène, sa valeur correspond parfois à uniquement un chiffre et d'autre fois à un nombre et une unité (word). Je propose de bien mettre juste une valeur sous forme de nombre pour @extent et l'unité sur unit.

En fait, la valeur de l'attribut @extent, comme je l'ai indiqué dans la présentation de l'issue, combine à la fois la valeur de l'attribut @quantity et celle de l'attribut @unit. Donc il faut choisir entre @extent (exemple: extent ="2 words") ou l'usage associé de @quantity et @unit (exemple: quantity = "2" unit="word"). Je préfère personnellement l'usage de @extent dans le cadre de notre corpus.

**Comment by Juliettejns** [comment]
Il a été choisi dans l'issue #39 d'utiliser les attributs @unit et @quantity.
