### ISSUE TITLE
Détermination des attributs à utiliser pour les éléments add, del, delSpan, subst, substJoin, restore_Version Génétique

### ISSUE THREAD

**Issue by PaulineChauvet** [axellelecroq/apollinaire-project#37]
Bonjour à tous,

Dans le même esprit que l'issue #36, je soumets au débat le choix et l'usage des attributs pour les éléments d'ajouts, de corrections, de suppressions, de substitutions et de restaurations soit "add", addSpan", "del", "delSpan", "subst", "substJoin", "restore", selon la sélection suivante:

- Attribut @rend pour indiquer comment l'élément en question a été rendu ou présenté dans le texte source (ex: barré, souligné, etc.)
- Attribut @place pour situer l'emplacement de l'élément encodé dans la page ou l'objet source (ex: marge droite, haut de page, etc).
- Usage optionnel, selon les cas, de l'attribut @status pour indiquer la conséquence de l'intervention, par exemple dans le cas d'un effacement, une biffure, qui inclut trop ou pas assez de texte, ou dans le cas d'un ajout, une insertion, qui reproduit une portion du texte déjà présent.
- Attribut @extent OU usage associé des attributs @unit et @quantity pour décrire les dimensions de l'intervention scripturale.

A débattre d'ici ce week-end afin de finaliser les réglages de notre ODD pour les versions génétiques! ;)

**Comment by ArsGeo** [comment]
Concernant l'attribut @rend, il semble qu'il soit pensé comme très large et n'a donc pas de valeurs fixes dans les guidelines, donc nous pouvons d'abord faire une liste de ce dont il doit rendre compte, par exemple : 
- _line_ pour "barré", 
- _overstrike_ pour "écrit en surcharge" (juste au-dessus du ou des mots),
- _overtyped_ pour "écrit par-dessus".
- 
Je n'ai pas décelé d'autres cas de figures possibles.

Etant donné que l'on rend compte des ajouts par la balise <add>, qui concerne donc aussi les ajouts en surcharge, nous pouvons éliminer _overstrike_.

Pour @place, les propositions des guidelines couvrent tous les cas de figures et sont explicites (et expliquées dans Oxygen en cas de doute), je pense que ceux-ci suffiront :
-  _above_ pour au-dessus de la ligne, 
- _below_ pour en-dessous de la ligne, 
- _top_ pour en haut de la page,
- _bottom_ pour en bas de la page,
- et _margin_ lorsque dans la marge. 

Enfin l'attribut @extent, me semble suffisant concernant la quantité de l'intervention, avec un nombre suivi de _chars_ pour caractères, _words_ ou _lines_.

**Comment by PaulineChauvet** [comment]
C'est parfait pour moi Arsène, les propositions de valeurs que tu soumets complètent parfaitement ma proposition initiale et me semblent solides et pertinentes pour notre corpus!

**Comment by HugoSchtr** [comment]
Okay pour moi aussi :) 
Comptez-vous indiquer ces choix dans l'ODD ? Avec une liste ouverte/fermée par exemple ?

**Comment by PaulineChauvet** [comment]
Oui, tout à fait Hugo! Cette issue a vocation à clarifier certains choix d'encodage spécifiques avant d'effectuer les derniers réglages de notre ODD. Nous ferons une liste restreinte, spécifierons les attributs optionnels/obligatoires, etc.

**Comment by axellelecroq** [comment]
Je ne suis pas d'accord avec la proposition d' @ArsGeo, pour barré je mettrais plutôt _strikethrough_. C'est d'ailleurs le mot utilisé dans la typographie pour dire barré.

**Comment by HugoSchtr** [comment]
@PaulineChauvet Oups oui effectivement la dernière phrase de ton premier post m'avait échappé, désolé !

**Comment by ArsGeo** [comment]
@axellelecroq _strikethrough_ est sûrement plus explicite oui ! Je considèrerais les vagues sur les mots comme des mots barrés aussi et vous ?

**Comment by axellelecroq** [comment]
Personnellement, de même mais je posais la question afin d'être sûre que nous soyons tous d'accord.

**Comment by Juliettejns** [comment]
Je suis d'accord avec tout ce qui a été dit! Il y a juste, comme dit dans l'issue précédente l'attribut @extent qui me gène. Je pense qu'il serait mieux de diviser sa valeur: il prend pour valeur un nombre, puis l'attribut unit prend pour valeur char, words ou line.

**Comment by Juliettejns** [comment]
Suite à la Pull Request #38 d' @ArsGeo je propose que les valeurs de l'attribut @rend soit rediscutées! Comme il l'a signalé, la valeur _overtyped_ semble un peu inutile dans le cas d'un imbriquement de balises tel que puisque renseigné par la valeur de rend de la balise add: 

```
<subst>
           <del extent="1" unit="word"><gap reason="illegible"/></del>
            <add rend="overtyped">pourri</add>
</subst>
```
Je propose de normaliser cela en choisissant pour quelle balise l'attribut est obligatoire dans ce cas.
Personnellement, j'aurais plutôt mis le rend sur del uniquement. Dans ce cas là, la valeur _overtyped_ ne serait pas utilisée.

**Comment by ArsGeo** [comment]
Je pensais aussi n'utiliser les attribut `@extent` et `@unit` uniquement dans le cas d'un passage supprimé ou remplacé, pour évaluer la perte.

Peut-être que dans le cas d'une substitution, l'on pourrait garder la valeur _overtyped_ dans `<del>`, pour caractériser quand même la suppression, et ne rien mettre dans le `<add>` qui suit ? Etant donné que le tout est déjà dans un élément `<subst>`, cela est peut-être induit ?

**Comment by PaulineChauvet** [comment]
Je l'ai évoqué dans une autre issue, mais pour faire une réponse complète: dans les bonnes pratiques TEI, l'usage d'@extent se substitue à celui des attributs unit et quantity. Donc associer extent et unit est valide au niveau du format tei, mais pas tout à fait conforme. Dans le cas d'une substitution, nous ne pouvons pas supprimer l'élément enfant "add", en utilisant "del" pour indiquer à la fois la suppression et l'ajout en jouant sur la valeur d'attribut. Ce n'est là non plus pas conforme aux bonnes pratiques et nous perdrions en clarté au niveau de la structuration des données encodées je pense.

**Comment by Juliettejns** [comment]
Merci beaucoup pour cet éclaircissement Pauline! Dans ce cas là, comme évoqué dans une autre issue, @PaulineChauvet, je propose d'utiliser plutôt  unit et quantity qu'un unique attribut extent, afin de pouvoir mieux contrôler les valeurs que ces attributs peuvent prendre. On pourrait par exemple réaliser des listes fermées de valeurs pour unit tel que _char, word, line_.
Je pense pas que @ArsGeo voulait supprimer la balise <add> mais  parlait plutôt des attributs à l'intérieur. De ce que je comprends, il propose, dans le cas d'une substitution, de mettre l'attribut rend ainsi:
```
<subst>
           <del rend="overtyped">d</del>
            <add>t</add>
</subst>
```

**Comment by Juliettejns** [comment]
Il a été choisi dans l'issue #39 d'utiliser les attributs @unit et @quantity.
