### ISSUE TITLE
Normalisation de la répartition des attributs dans une association des balises del et gap

### ISSUE THREAD

**Issue by Juliettejns** [axellelecroq/apollinaire-project#39]
Bonjour!
Suite aux remarques faites par @ArsGeo dans sa Pull Request #38, je propose de discuter de la répartition des attributs choisies dans les issues #37 et #36 dans une structure du type `<del> <gap/> </del>`. Nous avons deux solutions:

```
<del extent="1" unit="word">
          <gap reason="illegible"/>
</del>

```
```
<del>
       <gap extent="1" unit="word" reason="illegible"/>
</del>
```
J'ai une préférence pour la deuxième méthode, qui permet de regrouper tout ces éléments dans une seule et même balise. 

Qu'en pensez-vous?

**Comment by leaprs** [comment]
La deuxième méthode est également ce que nous avons choisi avec @axellelecroq pour les lettres. Je la trouve également plus complète que la première avec les attributs ``` @extent ``` et ``` @unit ``` directement sur la balise ``` <gap> ```. 

Pour les lettres, nous avons utilisé l'attribut ``` @quantity ``` à la place de ``` @extent ``` car il semblait plus approprié en raison qu'on pouvait réellement compter le nombre de caractères illisibles (https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.dimensions.html):
``` 
<gap quantity="11" unit="char" reason="illegible"/>
```
D'autre part, si on regarde les teiguidelines il semblerait que la figuration des attributs pour ``` <gap> ``` prendrait les formes suivantes (https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-gap.html) : 
```<gap quantity="4" unit="chars" reason="illegible"/> ```
ou
``` <gap extent="several lines" reason="lost"/> ```

Ainsi, l'attribut ``` @extent ``` informerait déjà d'une certaine unité assez approximative et par conséquent, l'attribut ``` @unit ``` serait pas nécessaire dès lors que ``` @extent ``` est utilisé. Je l'ai compris comme cela dans les exemples mais c'est à discuter :)

**Comment by axellelecroq** [comment]
Je rajoute, en plus de la remarque de @leaprs, que nous avons utilisé la balise `<gap>` indépendemment de la balise `<del>`.

**Comment by PaulineChauvet** [comment]
> La deuxième méthode est également ce que nous avons choisi avec @axellelecroq pour les lettres. Je la trouve également plus complète que la première avec les attributs `@extent` et `@unit` directement sur la balise `<gap>`.
> 
> Pour les lettres, nous avons utilisé l'attribut `@quantity` à la place de `@extent` car il semblait plus approprié en raison qu'on pouvait réellement compter le nombre de caractères illisibles (https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.dimensions.html):
> `<gap quantity="11" unit="char" reason="illegible"/>`
> D'autre part, si on regarde les teiguidelines il semblerait que la figuration des attributs pour `<gap>` prendrait les formes suivantes (https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-gap.html) :
> `<gap quantity="4" unit="chars" reason="illegible"/>`
> ou
> `<gap extent="several lines" reason="lost"/>`
> 
> Ainsi, l'attribut `@extent` informerait déjà d'une certaine unité assez approximative et par conséquent, l'attribut `@unit` ne serait pas nécessaire dès lors que `@extent` est utilisé. Je l'ai compris comme cela dans les exemples mais c'est à discuter :)

Merci Léa, cela rejoint ce que j'avais indiqué dans mon issue précédente, à savoir que l'usage de l'attribut @extent se substitue à l'usage associé des attributs unit et quantity. J'avais fait le choix d'extent dans l'encodage de notre échantillon des versions génétiques, mais en voyant ton exemple pour les lettres, unit et quantity sont peut être effectivement plus précis et donc préférables. Il est important que nous options collectivement pour ce choix entre les deux possibilités.

**Comment by PaulineChauvet** [comment]
> Je rajoute, en plus de la remarque de @leaprs, que nous avons utilisé la balise `<gap>` indépendemment de la balise `<del>`.
> Par exemple :
> 
> ```
> <p>[...]
> les zannis <gap quantity="7" unit="char" reason="illegible"/> napolitains
> [...]</p>
> ```
> 
> Ainsi la balise `<gap>` apparaît sans la balise `<del>`.

Oui, l'élément "gap" est utilisé dans le cadre de l'encodage de notre corpus pour renseigner les éléments illisibles de notre matériau source. Donc cela n'est pas forcément lié aux suppressions.

**Comment by ArsGeo** [comment]
D'accord, c'est ce que je me disais, nous garderions alors `<del>` pour notifier les suppressions humaines et gap lorsqu'un passage est illisible car le support est altéré. Quid cependant des suppressions humaines qui rendent le texte illisible ?

**Comment by PaulineChauvet** [comment]
Non, ce n'est pas tout à fait cela. "gap" n'est pas dédié spécifiquement aux suppressions mais à la mention de passages illisibles. Il n'y a pas d'interdépendance entre les deux. Il peut y avoir un élément "gap" dans un élément "del" mais pas nécessairement. Ce peut être également un élément imbriqué dans un add/addSpan, etc. ou une simple division. Quand le support est altéré, il faut utiliser l'élément gap avec l'attribut @agent. Les suppressions humaines qui rendent le texte illisible, c'est au moyen d'un élément del comprenant un élément gap avec l'attribut @reason = illegible.

**Comment by ArsGeo** [comment]
D'accord je comprends mieux, merci !

**Comment by Juliettejns** [comment]
Je suis complètement d'accord avec toi@leaprs! Si tout le monde est ok, je propose de fermer cette issue.
@PaulineChauvet Également d'accord avec toi pour ce qui est des attributs @quantity et @unit.
