### ISSUE TITLE
Normalisation xml:id pour lettres et articles

### ISSUE THREAD

**Issue by axellelecroq** [axellelecroq/apollinaire-project#40]
Bonjour à tous,

Il conviendrait de se mettre d'accord sur un choix d'`xml:id` afin de le normaliser dans tout notre encodage.
À noter qu'un xml:id ne peut pas commencé par un entier.
Voici plusieurs propositions discutées ensemble sans avoir fait de choix définitif : 
Pour les lettres: 
- `lettre_184-187` --> indique l'intervalle
- `lettre_184-185-186-187` --> indique tous les folios 

Pour les articles:
- `article2_201` --> pour l'article 2 du folio 201
- `article_201-202` --> pour un article sur deux folios différents

Personnellement et contrairement au nommage des fichiers, je pense que l'intervalle fait plus sens le cas des `xml:id`. Comme l'avait indiqué @D0riane, cela n'est peut-être pas nécessaire d'y afficher tous les folios sachant qu'au sein de l'encodage ils apparaissent dans l'attribut `@n` de nos balises. 
Néanmoins, tout cela mérite discussion avant décision.

**Comment by leaprs** [comment]
Pour ce qui est des intervalles, je suis d'accord de le mentionner dans le ``` @xml:id ``` mais pour le nommage des fichiers, d'indiquer tous les folios.
Soit pour le fichier lettre_185-186-187.xml (en l'occurence ça commence à 185 @axellelecroq  ;) ) avec l'xml:id : lettre_185-187

**Comment by D0riane** [comment]
Bonjour, 
Je suis d'accord également pour rester sur l'intervalle pour le xml:id. :)

**Comment by PaulineChauvet** [comment]
Bonjour à tous,

Je pense également qu'il faut indiquer l'intervalle dans le xml:id, mais aussi dans le nommage des fichiers .txt. Encore une fois, toujours dans une logique de respect des conventions, et par souci de clarté.

**Comment by axellelecroq** [comment]
S'il te plait @PaulineChauvet, peux-tu rajouter le lien vers cette convention que tu cites afin que tout le monde puisse s'informer et la lire ?

**Comment by PaulineChauvet** [comment]
C'est une convention de citation dans la recherche en SHS. Ce n'est pas écrit à un endroit en particulier, c'est une sorte de "jurisprudence" que l'on apprend au cours de notre formation de chercheur.

**Comment by PaulineChauvet** [comment]
> S'il te plait @PaulineChauvet, peux-tu rajouter le lien vers cette convention que tu cites dans cette issue ainsi que dans cette sur la [structure du corpus](https://github.com/axellelecroq/apollinaire-project/issues/21) afin que tout le monde puisse s'informer et la lire ?

Tu parles d'extent et de unit/quantity?

**Comment by HugoSchtr** [comment]
Okay pour l'intervalle dans le xml:id, pour moi l'information est claire de la sorte.

**Comment by leaprs** [comment]
L'intervalle est donc validé pour le xml:id, je clos cette issue.
