### ISSUE TITLE
Utilisation de l'élément "group" pour encoder l'intégralité des versions génétiques dans le même fichier .xml (valable aussi pour le dossier de presse)

### ISSUE THREAD

**Issue by PaulineChauvet** [axellelecroq/apollinaire-project#42]
Bonjour à tous,

Afin de conserver respecter l'intégrité des versions génétiques d'une part, du dossier de presse d'autre part, je vous propose d'utiliser l'élément "group", lequel contient "le corps d'un texte composite, regroupant une séquence de textes distincts (ou groupes de ces textes) considérés comme une unité" (cf teiguidelines, p. 178.)
Voici un exemple:
![Capture d’écran de 2021-02-13 18-53-28](https://user-images.githubusercontent.com/74914886/107857170-087e2300-6e2d-11eb-9265-3476cfb7e5f0.png)

Je pense qu'il sera difficile d'en faire l'économie si nous souhaitons conserver la structure originelle de notre corpus.

**Comment by Juliettejns** [comment]
Bonjour Pauline! 
Suite à ta Pull request je saisis mieux ce que tu veux dire! Je comprends l'utilité de group et trouve que cela segmente bien nos différents poèmes.
Cependant, je ne suis pas sûre que l'élément `<front>` soit absolument nécessaire, puisque, en soit,les informations  changent assez peu. Par contre, il me semble que ce système peut être assez intéressant pour l'encodage du dossier de presse, étant donné la variété de documents. Auquel cas, on pourrait utiliser ce système également pour l'encodage des poèmes, afin d'uniformiser notre travail.

**Comment by leaprs** [comment]
Merci @PaulineChauvet  pour cette PR qui permet d'y voir plus clair sur l'élément ```<group>```. 
Effectivement, comme l'a mentionné @Juliettejns, l'élément ``` <front> ``` apporte beaucoup de répétitions dans le code et serait pour moi, révélateur de l'ambiguité d'utiliser ```<group>``` qui semble induire l'utilisation de ```<text>```,  ```<front>``` et  ```<body> ``` pour chaque entité du groupe (cf. https://www.tei-c.org/release/doc/tei-p5-doc/fr/html/ref-group.html).

Pour les poèmes, je ne me prononce pas car on peut éventuellement considérer que chaque poème est une entité du dossier des manuscrits. 
En revanche, pour les articles et les lettres, je ne trouve pas beaucoup d'avantages à cette disposition. Dans mon sens, on ne peut pas considérer quelques lignes d'un article ou une lettre comme un entité propre qui légitimerait la création d'un text à part et la rédaction d'un front et body dont ces derniers sont l'intérêt même de l'utilisation de ```<group>```. D'autre part, cela rajouterait également des questions : que mettre un ``` <head> ``` pour les lettres ? 
Je crains que ça ne rajoute beaucoup de lignes de code et que l'on soit perdu entre une multitude d'éléments ```<text>```,  ```<front>``` et  ```<body> ``` s'il faut considérer que chaque article/lettre est une entité à part.

**Comment by axellelecroq** [comment]
Merci pour ta proposition d'encodage @PaulineChauvet , j'arrive mieux à comprendre comment tout se goupille.
Tout comme Léa, j'ai encore beaucoup de réticences à l'idée de mettre cela en place pour le dossier de presse. 
Les poèmes sont bien des entités à part entière, ils ont des titres tous et forment le recueil Alcools, ce n'est pas le cas des lettres qui elles n'ont pas de titre. 
Outre aloudir notre encodage pour le dossier de presse, je trouve que l'utilisation de `<group>` ne s'y prête pas vraiment. Je trouve que le teiHeader est suffisant dans notre cas. 
Aussi, il faut penser à la quantité d'éléments: il y a 8 poèmes manuscrits contre près de 40 lettres et articles mélangés. Je trouve que ce serait se rajouter une charge de travail supplémentaire pour ce qui est du dossier de presse.
Je ne trouve pas que cette proposition s'applique convenablement au dossier de presse malheureusement.

**Comment by Juliettejns** [comment]
J'avoue que je pense le contraire d'Axelle et Léa, quant à l'utilité de cet encodage pour le dossier de presse. Le `<front>` permet de décrire chaque article/lettre assez précisemment mais il est vrai qu'il faut aussi réfléchir à la charge de travail que cela représente. Donc je comprends votre point de vue!
Pour ce qui est des poèmes, je suis pour une homogénéité de notre encodage et aurai préféré ne pas trop s'éloigner de la structure du dossier de presse. Cependant, je pense que `<group>` reste particulièrement intéressant et je suis d'accord avec son utilisation! Le `<front>` me semble un peu superflu par contre car toujours identique. Vous avez [ici](https://www.tei-c.org/release/doc/tei-p5-doc/fr/html/examples-group.html) plusieurs exemples de l'utilisation de la balise `<group>`. On pourrait s'inspirer de cet encodage, qui n'utilise pas de front. À débattre!
```
<group>
 <text xml:id="t1-g1-t1" xml:lang="mi">
  <body xml:id="t1-g1-t1-body1">
   <div type="chapter">
    <head>He Whakamaramatanga mo te Ture Hoko, Riihi hoki, i nga Whenua Maori, 1876.</head>
    <p>…</p>
   </div>
  </body>
 </text>
 <text xml:id="t1-g1-t2" xml:lang="en">
  <body xml:id="t1-g1-t2-body1"
   corresp="#t1-g1-t1-body1">
   <div type="chapter">
    <head>An Act to regulate the Sale, Letting, and Disposal of Native Lands, 1876.</head>
    <p>…</p>
   </div>
  </body>
 </text>
</group>
```

**Comment by ArsGeo** [comment]
Etant donné que les poèmes manuscrits et le dossier sont deux entités différentes, je suis pour utiliser <group> au moins pour les manuscrits.

**Comment by PaulineChauvet** [comment]
Merci pour ce débat très riche! Je suis d'accord avec Juliette sur le fait qu'il serait mieux d'harmoniser notre choix de structuration globale en optant pour "group" à la fois pour le dossier de presse et pour le recueil de poèmes. Toutefois, s'il n'est vraiment pas envisageable pour vous de l'adopter pour le dossier de presse, je pense que la forme et l'hétérogénéité du recueil de versions préparatoires justifient voire imposent son usage, même indépendamment du dossier de presse.

Je trouve particulièrement intéressant d'opter pour une solution "hybride" avec un "front" réduit au minimum grâce à l'usage de pointeurs qui renverraient vers les informations de présentation déjà indexées dans le teiHeader (voir PR #49 ). Mais nous pourrions encoder dans le body de chaque sous-ensemble des éléments de description matérielle, au moyen d'un MsDesc et d'un physDesc (voir issue #51 )

Dans tous les cas, je pense que nous devons trancher cette question d'ici la fin de semaine idéalement, car elle détermine de nombreux réglages au niveau de l'ODD. Et sans ODD, nous ne pouvons toujours pas encoder avec l'intégration continue...

**Comment by Juliettejns** [comment]
Tout à fait d'accord avec toi @PaulineChauvet. Tes propositions me conviennent complètement pour ma part!

**Comment by ArsGeo** [comment]
Je pencherais pour ma part plus vers la solution "hybride" qui je pense rendrait l'encodage moins lourd !

**Comment by HugoSchtr** [comment]
J'ai fait un essai d'encodage pour ```<group>``` pour quelques articles du dossier de presse. J'ai suivi la doc TEI, mais je ne sais pas si c'est archi complet. Il manque le ```<teiHeader>``` également ! 
#58

**Comment by leaprs** [comment]
Comme l'élément ` <group>` a été accepté par tout le groupe suite aux propositions d'encodage effectués via les PR, je clos cette issue !
