### ISSUE TITLE
Index nom de personnes

### ISSUE THREAD

**Issue by axellelecroq** [axellelecroq/apollinaire-project#43]
Bonjour à tous,

après avoir encodé toutes les lettres que je devais faire, je me retrouve avec un index de personne très mélangé avec notamment les personnes expéditrices mais aussi les références littéraires ou historiques.
Sachant que pour le petit lot de lettres encodés, j'ai déj`entre 10 et 15 personnes à qui ont fait référence mais qui n'ont pas de rôle "actif" dans ce dossier de presse et je suppose que ce chiffre va fortement augmenté avec les articles, je pense qu'il serait judicieux de "ranger" ces personnes par catégorie. 

Je propose par exemple : 
```
<standOff>
      <listPerson type="receiver">
         <person xml:id="Apollinaire">
            <persName><forename>Guillaume</forename><surname>Apollinaire</surname></persName>
         </person>
      </listPerson>
      <listPerson type="senders">
         [...]
      </listPerson>
      <listPerson type="references">
         [...]
      </listPerson>
       <!-- ici on trouve index des lieux puis bibliographiques -->
</standOff>
```
Pour le coup, dans "receiver" il y aura juste Apollinaire mais je trouvais important de le mettre dans une catégorie à part.
Pour les articles, il pourrait avoir une catégorie "journalists" par exemple.

**Comment by HugoSchtr** [comment]
Oui, bonne idée ! 

Pour les articles de presse, il y a souvent des poètes autre qu'Apollinaire qui sont mentionnés. On pourrait envisager un type "poets" et un type "journalists," à voir ensuite si d'autres catégories se rajouteront lors de l'encodage des articles. D'ailleurs pour les articles de presse, je pense qu'on peut mettre Apollinaire dans la catégorie générale des poètes.

**Comment by axellelecroq** [comment]
Est-ce que pour les articles de presse, il ne s'agit pas du coup plutôt de références ?

**Comment by HugoSchtr** [comment]
Donc un type "references" plutôt tu penses ?

**Comment by HugoSchtr** [comment]
Je pense que vous pouvez garder le type "receiver." Je pense qu'il est bien d'indiquer le rôle de la personne indexée, et du coup pour les lettres ça marche complètement. Pareil pour "senders." Un index commun n'est peut-être pas obligatoire, car les personnes indexée dans les articles de presse ont un rôle différents de ceux que vous avez défini dans les lettres, ils deviennent passif et du coup effectivement ne sont plus que des références faites par le journaliste qui rédige. Quitte à avoir des doublons !

Ou alors, si effectivement un index commun est une meilleure direction, des catégories très générales seront efficaces. Tous les poètes dans une grosse catégorie "poets," les autres personnes dans "persons," les journalistes dans "journalists."

**Comment by axellelecroq** [comment]
Je trouve cela très dommage d'avoir des doublons et cela montre qu'il y a une erreur dans notre encodage.
J'ai fouillé dans les teiguidelines et il y a notamment l'élément `<listRelation>` qui permet de définir des rôles passifs ou actifs. 
Ainsi, on aurait une seule et même `<listPerson>` et le role des personnes elles-mêmes seraient définies dans la balise `<listRelation>`. D'après les [teiguidelines](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-listRelation.html), celle balise se place entre la dernière personne de `<listPerson>` et la balise fermante de cette même balise. 
Voici ce que serait une proposition avec l'utilisation de cette balise : 
```
<listPerson>
    [encodage des personnes]
    <listRelation type="dossier_de_presse">
            <relation name="article" active="#xml:id_des_journalistes" passive="xml:id_des_personnes_référencées"/>
            <relation name="lettre" active="#xml:id_des_expéditeurs" passive="#apollinaire_guillaume"/>
    </listRelation>
</listPerson>
```
Par contre la liste dans les attributs `@active` et `@passive` risque d'être très longue. Mais peut-être que quelqu'un a une idée pour diviser cela ?

**Comment by leaprs** [comment]
Pour ma part, il me semble que dès lors qu'on encode dans un même fichier, nos index doivent être unifiés. Pour ce qui est des ``` <listRelation>```, j'ai peur que çela ne craint plus d'ambiguïté que de clarté sur le rôle des noms cités et cela risque d'être peu lisible.

Je propose quelque chose, qui est en fait d'aller au plus simple et de généraliser, en ne mettant pas de ``` @type ``` sur notre ``` <listPerson>``` en faisant seulement un inventaire des noms trouvés. Les éléments de contexte seront apportés dans l'élément ``` <note>``` et pourquoi pas enrichir ```<person>``` avec les dates de mort et de naissance lorsque cela est trouvable. 
Il me semble que ce principe pourrait suffire en considérant que le personne, effectuant des recherches dans notre encodage, chercherait par exemple Nicolas Beauduin et trouverait son nom dans un élément ``` <div>``` qui par son ``` @type ``` et l'emplacement du dit nom dans l'encodage, lui donnerait des éléments de contexte supplémentaires.

Je vous propose cette idée car cela me semble difficile de faire coexister les attentes descriptives en terme d'index pour les articles et pour les lettres. Tout comme nous l'avions fait pour la structure globale de notre corpus, je pense que certains choix doivent être fait pour rendre le tout lisible.

**Comment by HugoSchtr** [comment]
@leaprs J'ai suivi ton idée pour mes encodages. Si on a la foi on pourrait classer ça alphabétiquement à la fin aha.

**Comment by leaprs** [comment]
On l'a déjà fait, vous pouvez regarder le notre pour un possible copier/coller s'il y a les mêmes noms ahah

**Comment by axellelecroq** [comment]
Du coup, pour conclure cette PR, on laisse tomber `<listPerson>` et en encode les dates de naissance et de mort des personnes en plus ? 
Par contre de quelle manière souhaitez-vous encoder les dates de décès et de naissance ? car les balises `<death>` et `<birth>` ne sont pas acceptées dans la balise `<note>`. Est-ce que cela vous semblerez correct d'utiliser les attributs `@from` et `@to` directement dans la balise `<person>`  (ces attributs ne sont pas acceptés dans `<person>`) ? 
Par exemple : 
```
<person xml:id="carco_francis">
            <persName from="1886" to="1958"><forename>Francis</forename><surname>Carco</surname></persName>
            <note>Écrivain, poète, journaliste et parolier français. </note>
         </person>
```

**Comment by HugoSchtr** [comment]
J'ai trouvé ça dans les guidelines TEI pour encoder la naissance et la mort d'une personne dans ```<person>``` : 

```XML
         <person xml:id="goethe_johann_wolfgang_von">
            <persName><forename>Johann
                  Wolfgang</forename><nameLink>von</nameLink><surname>Goethe</surname></persName>
            <event type="birth">
               <p>Né en 1749, à Francfort, Allemagne.</p>
            </event>
            <event type="death">
               <p>Mort en 1832 à Weimar, Allemagne.</p>
            </event>
            <note>Romancier, dramaturge, poète, scientifique, théoricien de l'art et homme d'Etat
               allemand.</note>
         </person>
```

Ou plus simple : 

```XML
         <person xml:id="goethe_johann_wolfgang_von">
            <persName><forename>Johann
                  Wolfgang</forename><nameLink>von</nameLink><surname>Goethe</surname></persName>
            <birth>Né en 1749 à Francfort, Allemagne.</birth>
            <death>Mort en 1832 à Weimar, Allemagne.</death>
            <note>Romancier, dramaturge, poète, scientifique, théoricien de l'art et homme d'Etat.</note>
         </person>
```

**Comment by axellelecroq** [comment]
La deuxième proposition me convient plus, je la trouve moins lourde ! Et je suis d'accord pour la mettre en place.

**Comment by HugoSchtr** [comment]
Okay alors, on part sur ça ! Issue closed :)
