### ISSUE TITLE
Encodage des copies - lettres dossier de presse

### ISSUE THREAD

**Issue by leaprs** [axellelecroq/apollinaire-project#46]
Bonjour à tous, 
Ultime question concernant les copies de lettres trouvées dans le dossier de presse. D'après la structure décidée en groupe, l'attribut ``` @subtype ``` endosse le rôle de signaler la copie. Ainsi, pour le folio 188 qui est la copie du folio 190 : 
```
<div type="letter" n="188" xml:id="lettre_188">
      <pb type="recto" subtype="copy" facs="https://gallica.bnf.fr/ark:/12148/btv1b525088021/f188.item.r=Apollinaire%20manuscrits.zoom"/>
</div>
```
Je pensais qu'il serait intéressant de faire un lien vers l'original mais cela me semble difficile à mettre en place et du coup, je m'interroge sur la pertinence d'encoder les copies. Nous pouvons aussi garder l'encodage en l'état mais cela me semble un peu minimal, qu'en pensez-vous ? Avez-vous des idées ?

**Comment by axellelecroq** [comment]
Je suis d'avis de ne pas encoder les copies. Je pense qu'il s'agit d'un souci de numérisation et que du coup ce n'est pas intéressant de les faire apparaître dans notre encodage. 
Comme toi, je trouverai ça intéressant si on pouvait faire un renvoi à l'originale mais comme cela semble difficile à mettre en place comme tu l'as indiqué, il serait peut-être judicieux de mettre de côté ces copies.

**Comment by D0riane** [comment]
Pourrait on envisager l'utilisation de l'attribut `@sameAs` dans le `<div>` qui pointerait vers le `@xml:id`de la lettre originale ? 
Exemple fictif : 

<div type="letter" n="188" xml:id="lettre_188" sameAs="#lettre_190">
            <pb type="recto" subtype="copy" facs="https://gallica.bnf.fr/ark:/12148/btv1b525088021/f188.item.r=Apollinaire%20manuscrits.zoom"/>
         </div>
         
         <div type="letter" n="190" xml:id="lettre_190">
            <pb type="recto" facs="https://gallica.bnf.fr/ark:/12148/btv1b525088021/f190.item.r=Apollinaire%20manuscrits.zoom"/>
         </div>

**Comment by PaulineChauvet** [comment]
Je suis complètement d'accord avec la dernière proposition de Doriane, et pense que nous devons encoder les informations sur les copies, aussi minimales soient-elles, toujours dans un souci de respect d'intégrité du matériau source.

**Comment by axellelecroq** [comment]
Dans le cas de la proposition de @D0riane, doit-on copier l'encodage de la lettre aux deux endroits ou bien un seul endroit suffit? 
Si on adopte cette proposition, je trouverai cela redondant de trouver l'encodage à deux endroits différents et je mettrais plutôt dans la balise non de la copie mais de la lettre vers qui la copie est dirigée, dans le cas de l'exemple dans la `<div>` de la lettre 190 car c'est vers quoi la copie est dirigée. Qu'en pensez-vous?

**Comment by leaprs** [comment]
@D0riane, je ne connaissais pas l'existence de l'attribut ``` @sameAs ``` et en effet, son utilisation est légitime ! 
Seul petit hic, mes ``` id ``` de lettres correspondent à la lettre entière. Or, dans les cas de copies, c'est souvent un folio de la lettre qui est copié. Je m'explique : pour cette exemple, le folio 188 est une copie du folio 190 qui correspond à la lettre,  ``` xml:id="lettre_190-191" ```. Dans notre système de ``` xml:id ```, nous ne renseignons jamais pour les lettres, le folio comme entité seule. Cela ne me semble pas un problème que de renvoyer à l'entière lettre, du moment qu'on renvoie à une lettre, mais à discuter.

Pour ce qui est de ta question @axellelecroq, je pensais effectivement encoder une seule fois la lettre "complète" et pour les copies de folios, laisser la ``` <div> ``` vide en indiquant par le biais de ``` <pb> ``` qu'il s'agit d'une copie : 
Cela donnerait cette forme finale : 
```
<div type="letter" n="188" xml:id="lettre_188" sameAs="#lettre_190-191">
      <pb type="recto" subtype="copy" facs="https://gallica.bnf.fr/ark:/12148/btv1b525088021/f188.item.r=Apollinaire%20manuscrits.zoom"/>
</div>
```
Qu'en pensez-vous ?
