### ISSUE TITLE
Normalisation xml:id pour références indexées

### ISSUE THREAD

**Issue by axellelecroq** [axellelecroq/apollinaire-project#47]
Bonjour à tous,

nous nous sommes mis d'accord pour le [nommage des `xml:id`](https://github.com/axellelecroq/apollinaire-project/issues/40) des articles, lettres et manuscrits, reste à présent à normaliser les `xml:id` des références indexées, j'entends par là les `xml:id` pour les noms des personnes, les lieux et les références bibliographiques.

1. De manière générale, pour les noms des personnes, je propose de mettre le nom de famille seul en tant `xml:id` avec une majuscule en début de nom. Par exemple, pour Fernand Fleuret, l'`xml:id` serait `Fleuret`. 
2. Cette règle pourrait s'appliquer pour les noms de lieux, `Paris` pour Paris. Mais que fait-on des noms de lieux composés comme Cap d'ail ou Criquetot L'Esneval? Je pense que pour le coup il s'agirait de faire du cas par cas et de choisir de manière un peu arbitraire mais que cela reste compréhensible pour tous. Dans ces cas précis, j'ai choisi par exemple `Cap-ail` en `xml:id` car il pourrait y avoir plusieurs Cap et seulement `Criquetot` pour Criquetot L'Esneval car je considérais que c'était suffisamment explicite. 
3. Pour les noms de références bibliographiques (ainsi que les références aux poèmes d'_Alcools_), j'ai fais le choix, discutable, de tout mettre en minuscule, que tous les mots apparaissent et que chaque espace soit représenté par un tiret. Ainsi l'`xml:id` pour le poème Le voyageur serait `le-voyageur` et pour l'ouvrage _La légende de la mort_ de Anatole Le Braz (oui, oui il est mentionné dans une lettre), l'xml:id serait `la-légende-de-la-mort`. 

Tout cela sont seulement des propositions, je suis preneuse d'améliorations et d'idées afin de normaliser au mieux les `xml:id` afin de faciliter la mise en commun des articles et des lettres. 
C'est une discussion qui est ouverte à tous, car les `xml:id` des poèmes seront les mêmes que ceux utilisés pour les poèmes manuscrits.

**Comment by Juliettejns** [comment]
Bonjour Axelle!
Pour ce qui est des poèmes manuscrits, cette normalisation me convient. Elle a le mérite de ne pas être très compliquée à retenir et à comprendre.
Pour les noms de personnes, j'aurais plutôt proposé de mettre la première lettre du prénom en majuscule avant le nom de famille, par exemple "FFleuret" pour Ferdinand Fleuret que tu prends en exemple, au cas où il y a plusieurs personnes avec le même nom. Mais il ne semble pas que ce soit le cas sur notre corpus donc ta proposition me semble tout de même très bien!

**Comment by D0riane** [comment]
Bonjour, 
Je trouve les propositions d' @axellelecroq très intéressantes. Au cas par cas : 
- `@xml:id` pour les personnes : Je pense que la réflexion de @Juliettejns est très légitime et donc je serai d'avis d'ajouter effectivement par précaution la première lettre du prénom en plus du nom.
- `@xml:id` pour les lieux : pour éviter toute confusion, je pense que écrire tout le nom du lieu avec des tirets pour séparer les mots est une bonne option. Je propose de tout mettre en minuscule (comme pour les poèmes) pour simplifier au maximum la référence. 
- `@xml:id` pour les poèmes : ça me semble très bien comme ça : précis et simple à la fois !

**Comment by axellelecroq** [comment]
est-ce que du coup ça vaudrait pas le coup de tout mettre en minuscule même les noms de personnes ? 
Tout serait ainsi normalisé :
- personne : `ffleuret` pour Ferdinant Fleuret (avec la première lettre du prénom comme l'a proposé @Juliettejns)
- lieu : `cap-d-ail` pour Cap d'Ail
- poème : `le-mal-aimé` pour _Le mal aimé_

Est-ce que cela conviendrait à tout le monde ?

**Comment by D0riane** [comment]
Effectivement tout mettre en minuscule semble le mieux. 
Je suis d'accord également pour mettre le nom avant et ajouter un tiret entre le nom et la première lettre du nom pour que ce soit plus explicite. 
Donc pour moi, les meilleures options sont : 
- personne : `fleuret-f` pour Ferdinand Fleuret.
- lieu : `cap-d-ail` pour Cap d'Ail.
- poème : `le-mal-aimé` pour Le mal aimé.

**Comment by PaulineChauvet** [comment]
Bonjour à tous,

Merci Axelle pour ta proposition de départ.
Concernant les références littéraires, dont les poèmes, je suis d'accord pour l'intitulé en minuscule mais avec chaque mot séparé par un underscore, non un tiret. Idem pour l'indexation des lieux. C'est un point de détail mais il est plutôt habituel de voir cette forme typographique que les tirets simples.
Enfin, s'agissant des personnes, je pense que le plus pertinent serait votre dernière proposition mais là encore, avec un underscore ainsi que le prénom complet sans accentuation pour plus de clarté et de lisibilité:

- personne: fleuret_ferdinand pour Ferdinand Fleuret

**Comment by axellelecroq** [comment]
Après avoir pris les remarques de tout le monde, cela se présenterait donc comme suit :  
- personne : `fleuret-ferdinand` pour Ferdinand Fleuret.
- lieu : `cap-d-ail` pour Cap d'Ail.
- poème : `le-mal-aimé` pour Le mal aimé.

Est-ce que tout le monde est d'accord avec cette proposition ? 
Mettez un 👍  si oui et si non, toutes les propositions sont bonnes à prendre !

**Comment by axellelecroq** [comment]
La majorité semble d'accord, je ferme l'issue et j'ajoute ces règles dans le [document sur les règles de nommage](https://github.com/axellelecroq/apollinaire-project/blob/main/documentation/regles_nommage.md).
