### ISSUE TITLE
Renseigner la foliation pour les poèmes des manuscrits préparatoires

### ISSUE THREAD

**Issue by ArsGeo** [axellelecroq/apollinaire-project#51]
Bonjour à tous, 

Nous nous demandions comment renseigner la foliotation (qui est bien les numéros des folios du manuscrit et non pas le numéro de la vue Gallica !) de chaque poème, qui est habituellement une information importante en codicologie.

Etant donné que notre élément `<div>` correspondant à un poème est déjà assez chargé, nous pensions le renseigner dans `<physDesc>` dans la mesure où l'on utiliserait l'élément `<group>` pour notre corpus et que l'on pourra en avoir un pour chaque poème.

Qu'en pensez-vous ?

**Comment by PaulineChauvet** [comment]
Bonjour Arsène,

Je propose la méthode d'encodage suivante pour renseigner la foliotation, dans le cadre d'un élément parent "group":
![ExempleFoliation_Group](https://user-images.githubusercontent.com/74914886/108073210-0ce25000-7068-11eb-8d79-034c908e145e.png)

Cela permettrait de réserver l'attribut @n à la numérotation, et de ne pas l'utiliser pour renseigner des informations de nature distincte dans le même encodage.

**Comment by Juliettejns** [comment]
Ta proposition me convient tout à fait @PaulineChauvet! 
Pour ce qui est de la numérotation dont tu parles? S'agit-il bien de la pagination?

**Comment by ArsGeo** [comment]
Je suis d'accord aussi !

Je crois que Pauline parlait des utilisations que nous faisons déjà de @n, à savoir notifier le numéro de la vue sur Gallica et le numéro de la strophe.

J'ai deux dernières questions : pensez-vous qu'il serait pertinent et faisable de rajouter en plus la position du poème dans le manuscrit ? Par exemple le Mal-Aimé se trouve aux f.2r à 14v ?

Et faudra-t-il renseigner les caractéristiques du manuscrit de chaque poème dans le msDesc ? Etant donné que le manuscrit est le même pour tous, ce ne serait peut-être pas pertinent.

**Comment by PaulineChauvet** [comment]
> Je suis d'accord aussi !
> 
> Je crois, Pauline, concernant les utilisations que nous faisons déjà de @n, à savoir notifier le numéro de la vue sur Gallica et le numéro de la strophe, il ne pose pas problème car cela reste de la numérotation ?

Oui, tout à fait. Alors que dans le cas de la foliotation, il s'agit d'un élément de description physique de la source à part entière.
