### ISSUE TITLE
Structuration des poèmes: représentation d'un changement de page

### ISSUE THREAD

**Issue by Juliettejns** [axellelecroq/apollinaire-project#55]
Bonjour à tous!

J'ouvre cette issue afin de discuter de la normalisation de l'encodage des changements de page pour les poèmes.
D'après nos prototypes d'encodage, nous avons choisi de la représenter soit avec un div:
`<div type="recto" n="4" facs="https://gallica.bnf.fr/ark:/12148/btv1b52505641f/f25">`
soit avec un pb:
`<pb n="4" facs="https://gallica.bnf.fr/ark:/12148/btv1b52505641f/f25"/>`

Si l'on se refère aux choix d'encodage du dossier de presse à ce propos, (issues #33 et #34), la balise pb est utilisée pour les vues sur Gallica , tandis que la balise div est employée pour symboliser chaque page. Ainsi, il serait, il me semble, intéressant, d'homogénéiser notre encodage en réutilisant les choix du dossier de presse. J'ajoute un exemple d'encodage du dossier de presse afin de voir la répartition entre les deux balises et les attributs utilisés:
```
<div type="letter" n="198,199" xml:id="lettre_198-199">
            <pb type="recto"
               facs="https://gallica.bnf.fr/ark:/12148/btv1b525088021/f198.item.r=Apollinaire%20manuscrits"/>

```
Sachant que certaines strophes sont à cheval sur deux pages, je trouve la balise pb particulièrement intéressante puisqu'elle permet de symboliser le changement de page sans avoir d'imbrication de balises. Autrement, il est toujours possible, si l'on utilise la balise div, d'encoder  une strophe sur deux pages en utilisant l'attribut part dans la balise lg (les valeurs utilisées sont proposées par Oxygen et signifient Initial pour I et Final pour F):
```
<div type="recto" n="4" facs="https://gallica.bnf.fr/ark:/12148/btv1b52505641f/f25">
[...]
 <lg type="septain" n="1" part="I">
                    <l>Voie lactée ô sœur lumineuse</l>
                    <l>Des blancs ruisseaux de Chanaan</l>
                    </lg>
                </div>
                <div type="verso" n="5" facs="https://gallica.bnf.fr/ark:/12148/btv1b52505641f/f26">
                    <lg type="septain" n="1" part="F">
                        <l>Je me souviens d’une autre année,</l>
                        <l>C’était l’aube d’un jour d’avril.</l>
                        <l>J’ai chanté ma joie bien-aimée,</l>
                        <l>Chanté l’amour à voix virile,</l>
                        <l> Au moment d’amour de l’année.</l>
                    </lg>
                </div>

```
Quelle solution préférez-vous?

**Comment by ArsGeo** [comment]
J'ai relevé un problème sous-jacent dont il faudrait s'occuper avant : veut-on renseigner, dans l'élément `<div>` le folio, ainsi : 

`<div type="recto" n="4" facs="https://gallica.bnf.fr/ark:/12148/btv1b52505641f/f25">`

Ou bien le numéro de la vue sur Gallica, ainsi :

`<div type="poeme" n="63" facs="https://gallica.bnf.fr/ark:/12148/btv1b52505641f/f63.item.r=Manuscrit%20Apollinaire">`

**Comment by HugoSchtr** [comment]
Bonjour ! 
On a beaucoup réfléchi aux changements de page pour le dossier de presse effectivement. La décision a été prise en fonction de l'hétérogénéité que représente ce document (lettres et articles de presse). 

Je suis d'accord avec ta proposition Juliette pour homogénéiser l'encodage ! 

@ArsGeo Bonne question ! Pour le dossier de presse, ```@n``` indique la vue sur Gallica.

**Comment by leaprs** [comment]
@Juliettejns, je pense que tes arguments pour l'utilisation de ``` <pb>``` dans une structure analogue au dossier de presse sont convaincants. Cependant, si effectivement l'attribut ``` @part``` dans la balise ``` <lg>``` peut endosser ce rôle, il me semble que ce serait une économie et l'encodage gagnerait en efficacité en indiquant directement cette information directement sur la balise donc à discuter :)

Je complète la réponse de @HugoSchtr, effectivement ``` @n``` représente la vue sur Gallica car pour le dossier de presse, s'agissant de documents éparses et interchangeables, la signification d'une linéarité importe moins. De plus, le document n'est pas à proprement classé par folios sur Gallica.

**Comment by ArsGeo** [comment]
Je suis d'accord avec Léa pou utiliser l'attribut `@part` de `<lg>`, mais je me rends compte que le numéro de folio semble difficile à intégrer...

**Comment by PaulineChauvet** [comment]
Bonjour à tous,

Je ne pense pas qu'il soit pertinent de renseigner le numéro de vue sur Gallica puisque l'on renvoie immédiatement après vers le lien de la numérisation avec @facs. Aussi, j'opterai pour l'indication du numéro de folio.
Pour répondre à Juliette sur la structure et l'indication du changement de page, je trouve que la meilleure solution est celle de l'harmonisation avec le dossier de presse. En revanche, je crois qu'il n'est pas possible d'indiquer un "pb" dès la première page encodée car "pb" signale bien un changement de page depuis la page actuelle.

**Comment by ArsGeo** [comment]
Je serais aussi d'avis de remplacer le numéro de vue sur Gallica par le numéro de folio ; je trouve que cela est plus pertinent et justifié pour les poèmes manuscrits.

**Comment by Juliettejns** [comment]
Merci pour toutes ces propositions!
Si je résume ce qui a été:  on utilise donc les mêmes balises que le dossier de presse pour encoder une page. Je suis d'accord avec @ArsGeo et @PaulineChauvet pour indiquer le numéro de folio plutôt que le numéro de vue sur Gallica. L'attribut facs de la balise pb a pour valeur l'url de la vue Gallica.

Pour ce qui est de l'attribut part de la balise lg, je ne suis pas sûre de comprendre ce que vous avez dit @leaprs et @ArsGeo. Pour moi, cet attribut permet seulement de dire que l'élément est divisé en deux, puisque l'on est obligé de refermer la balise lg une première fois avant de mettre la balise fermante div de la première page. C'était donc une proposition d'encodage au cas où on avait des strophes à cheval sur deux pages mais qui est discutable effectivement si l'attribut vous embête:)

**Comment by leaprs** [comment]
@Juliettejns effectivement ce n'est pas dans ce sens là, je voulais dire que je trouvais son utilisation pertinente dans votre encodage !
