### ISSUE TITLE
Encodage du tampon de bibliothèque dans le msDesc

### ISSUE THREAD

**Issue by Juliettejns** [axellelecroq/apollinaire-project#56]
Bonjour à tous!

Suite à la PR de Pauline concernant le tei header des poèmes manuscrits (#49), je cherche à encoder le tampon de bibliothèque dans le msDesc, comme décidé dans l'issue #27. 
Je n'ai trouvé que [ces informations](https://www.tei-c.org/release/doc/tei-p5-doc/fr/html/MS.html#msph3) concernant l'encodage d'une estampille, plutôt dans le text que dans le teiheader donc.
Je pense qu'il serait intéressant de l'encoder dans le physdec mais si il existe bien un sealDesc, il n'y a pas de stampDesc. J'ai donc encodé l'élémént dans une balise `<accMat>` à partir des informations données [ici](http://bibale.irht.cnrs.fr/44365):

```
             <accMat>
                    <stamp xml:id="estampille_BnF">
                        <mentioned>Biblioth. nationale MSS</mentioned>
                        <dimensions>
                           <height unit="mm">12</height>
                        </dimensions>
                        <note>Petite estampille ovale (en hauteur) 
du département des manuscrits de la Bibliothèque nationale (aujourd'hui BnF)
 après <date>1870</date></note>
                     </stamp>
                  </accMat>
```

Qu'en pensez-vous? On peut discuter de l'emplacement de la balise, ainsi que du nommage de son xml:id et des différents éléments encodés la décrivant, qui, je pense, peuvent être améliorés.

**Comment by HugoSchtr** [comment]
Pour le xml:id, on peut peut-être indiquer directement une information de date dedans. Par exemple "estampille_bnf_1870", ou "estampille_bnf_après_1870" pour indiquer cette indication temporelle. Mais l'id se rallonge. 

Je pense qu'un ```@facs``` serait utile dans ```<stamp>``` pour indiquer http://bibale.irht.cnrs.fr/44365
```XML
<stamp xml:id="estampille_BnF" facs="http://bibale.irht.cnrs.fr/44365">
```

**Comment by axellelecroq** [comment]
Même si il n'y a pas de balise pour les tampons comme il en existe pour les sceaux, tu indiques malgré tout le fait que ce soit un tampon avec la balise `<stamp>`. Je trouve ta proposition pertinente.
En parcourant les teiguidelines, j'ai vu que la balise `<stamp>` pouvait être contenu dans `<institution>`, elle même contenu dans le `<msDesc>`. Peut-être que ça peut être une alternative d'encodage aussi?
En reprenant l'encodage de @PaulineChauvet et la proposition de @Juliettejns cela donnerait cela : 
```
<msIdentifier>
                  <country>France</country>
                  <institution><name>Bibliothèque nationale de France. </name>
                     <stamp xml:id="estampille_BnF">
                        <mentioned>Biblioth. nationale MSS</mentioned>
                        <dimensions>
                           <height unit="mm">12</height>
                        </dimensions>
                        <note>Petite estampille ovale (en hauteur) du département des manuscrits de
                           la Bibliothèque nationale (aujourd'hui BnF) après
                           <date>1870</date></note>
                     </stamp></institution>
                  <repository>BnF. Département des Manuscrits.</repository>
                  <altIdentifier>
                     <idno>NAF 25608</idno>
                  </altIdentifier>
                  <altIdentifier>
                     <idno>ark:/12148/btv1b52505641f</idno>
                  </altIdentifier>
               </msIdentifier>
```

Aussi je trouve cela bien de faire directement référence au site de l'IRHT comme l'a proposé Hugo.

**Comment by Juliettejns** [comment]
Très bonne remarque @HugoSchtr, je suis tout à fait d'accord avec la référence directe au site de l'IRHT ainsi que le nommage de l'xml:id. Et en effet, `<accmat>` n'est pas contenu dans le `<supportDesc>`, la balise `<stamp>` n'y étant pas autorisée dans les teiguidelines directement, il faudrait l'imbriquer dans une balise` <p>`, comme l'a fait Arsène! 
Ton encodage est intéressant @axellelecroq, surtout dans le cas des poèmes manuscrits où il n'y a qu'un seul tampon! Mais, étant donné que le dossier de presse en a plusieurs, j'ai pensé qu'il pouvait être intéressant de pouvoir rassembler tout les tampons dans la balise `<accmat>` (et auquel cas, on pourrait reprendre cette méthode pour les poèmes manuscrits). À moins que vous ne souhaitiez encoder que le tampon de la BnF dans le msDesc et, dans ce cas là, ton encodage me convient complètement!

**Comment by axellelecroq** [comment]
Sauf erreur de ma part, il me semble qu'il y a qu'un seul tampon dans le dossier de presse. Les autres tampons sont des tampons de poste et sont, par conséquent encodés directement dans le `<body>`.
Les deux méthodes sont bonnes je pense : 
- je trouve la tienne intéressante si on indique plusieurs tampons dans le `teiHeader` comme tu l'as précisé.
- je trouve la mienne intéressante si on considère que ce tampon appartient à la BnF comme une marque de son institution.
Ce serait intéressant de recevoir l'avis des autres!

**Comment by ArsGeo** [comment]
J'avais moi-même tenté d'encoder ce tampon en le plaçant dans <support>, ainsi : 

```
<physDesc>   
      <objectDesc form="codex">
                     <supportDesc>
                        <support>Papier, <stamp>utilisation quasi-systématique d'une estampille sur laquelle on lit "Bibliothèque Nationale MSS"
                              sur les pages du document.</stamp></support>
```

Les deux méthodes conviendraient effectivement, mais je trouve aussi très intéressant le fait de lier le tampon à l'institution, tant que l'on précise qu'il apparaît régulièrement.

Et oui @HugoSchtr, cela sortirait ma balise `<stamp>` de _<supportDesc>_ !

**Comment by Juliettejns** [comment]
@axellelecroq Merci pour cette précision! Effectivement, dans ce cas-là, je trouve ta proposition de lier le tampon à l'institution plus judicieuse:)

**Comment by PaulineChauvet** [comment]
Je suis tout à fait d'accord avec la dernière proposition d'Axelle, qui mêle les suggestions très judicieuses du reste du groupe mais en ajoutant la pertinence de l'élément "institution" que je trouve beaucoup plus adapté.
Il s'agit toujours de la même estampille, je pense que nous pouvons nous contenter de l'indiquer une seule fois dans le teiHeader du recueil de poèmes, et dans le teiHeader du dossier de presse. Ceci dans un souci de non-redondance des données.

**Comment by axellelecroq** [comment]
``` 
           <msIdentifier>
                  <country>France</country>
                  <institution><name>Bibliothèque nationale de France. </name>
                     <stamp xml:id="estampille_bnf_1870" facs="http://bibale.irht.cnrs.fr/44365">
                        <mentioned>Biblioth. nationale MSS</mentioned>
                        <dimensions>
                           <height unit="mm">12</height>
                        </dimensions>
                        <note>Petite estampille ovale (en hauteur) du département des manuscrits de
                           la Bibliothèque nationale (aujourd'hui BnF) après
                           <date when="1870">1870</date></note>
                     </stamp></institution>
                  <repository>BnF. Département des Manuscrits.</repository>
                  <altIdentifier>
                     <idno>NAF 25608</idno>
                  </altIdentifier>
                  <altIdentifier>
                     <idno>ark:/12148/btv1b52505641f</idno>
                  </altIdentifier>
               </msIdentifier>
```
👍 si c'est l'encodage qui vous convient !

**Comment by leaprs** [comment]
@axellelecroq merci pour cette précision, c'est ok pour moi !
