### ISSUE TITLE
Encodage en tête et pied de page journaux pour les articles

### ISSUE THREAD

**Issue by D0riane** [axellelecroq/apollinaire-project#60]
Bonjour à tous, 

Après avoir avancé dans mes encodages, je suis confrontée à un problème que je ne parviens pas à résoudre. Dans le cas des articles de plusieurs pages, je me trouve avec les informations de pied de page et d'en tête liées à la mise en page du journal et non à l'article. 

https://gallica.bnf.fr/ark:/12148/btv1b525088021/f148.item : par exemple ici nous avons en pied de page "Envoi franco du Catalogue complet sur demande". Lorsque j'encode l'article, je ne sais où placer cette mention qui se trouve au milieu alors du paragraphe. De même pour l'entête sur la page suivante.

https://gallica.bnf.fr/ark:/12148/btv1b525088021/f153.item : par exemple ici nous avons l'en-tête et la numérotation. Lorsque j'encode l'article, ces informations se trouvent du coup au milieu du paragraphe. 

Que faire donc de ces en tête et de ces pieds de page ?

**Comment by HugoSchtr** [comment]
Salut ! 
Merci de poser cette question, c'est vrai que j'ai rapidement mis de côté ces infos dans mes encodages. Je me suis en effet demandé si on avait besoin de garder ces infos pour respecter le sens des articles. 

Par exemple pour ce folio : https://gallica.bnf.fr/ark:/12148/btv1b525088021/f162.item.r=Apollinaire%20manuscrits -> j'ai omis la numérotation, les dessins. 

Et pour cet article de _La Phalange_ : https://gallica.bnf.fr/ark:/12148/btv1b525088021/f158.item.r=Apollinaire%20manuscrits -> j'ai omis l'en-tête.

Je vais regarder les guidelines pour voir comment on pourrait les encoder si jamais on souhaite garder ces infos. :)

**Comment by axellelecroq** [comment]
Peut-être que la [balise `<trailer>`](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-trailer.html) pourrait être utilisée dans ce cas ?

**Comment by D0riane** [comment]
`<trailer>`ne fonctionne pas... Enfaite, j'ai des changements de pages au milieu d'un paragraphe. Or, le changement de page sous entend le pied de page de la page actuelle et l'en tête de la nouvelle page. 
```
<p>
   <lb/>début paragraphe
      [pied de page]
  <pb facs="..."/>
      [en-tête]
  <lb/>suite du paragraphe
```

**Comment by HugoSchtr** [comment]
J'avais rencontré ce problème pour le contrôle en TEI. 
Est-ce qu'un simple ```<p>``` avec un ```@type``` pour préciser "footer" ou "header" serait envisageable ?

**Comment by axellelecroq** [comment]
Ah ! Dommage !
Sachant qu'il s'agit d'un élément qui se répète, peut-être serait-il utile de l'encoder une seule fois pour tout l'article.
Nous pouvons peut-être utiliser [`<metamark>`](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-metamark.html) : 
```<metamark>Le mois du poète</metamark>
[encodage de tout l'article]
```
Pour la numérotation de page, nous pouvons l'indiquer directement dans une balise `<note>` au sein de la `<metamark>`.

Pour la note de bas de page, je n'ai malheureusement aucune proposition.

**Comment by D0riane** [comment]
L'attribut `@type` n'est pas disponible pour `<p>`. 
Par contre `<metamark>` fonctionne et j'ai décliné l'attribut `@function` pour indiquer footer ou header. Par exemple :
```
<metamark function="footer" rend="align(center) bold">Envoi franco du Catalogue complet sur demande</metamark>
```
Merci beaucoup pour vos propositions !

**Comment by HugoSchtr** [comment]
Super ! Je modifie mes encodages selon ta solution, merci !

**Comment by leaprs** [comment]
J'arrive un peu tard, mais je valide ta dernière proposition @D0riane !
