### ISSUE TITLE
Encodage des articles ne concernant pas alcools

### ISSUE THREAD

**Issue by D0riane** [axellelecroq/apollinaire-project#61]
Bonjour à tous, 
Dans mon corpus d'article, certaines coupures de presse ne concernent que en partie Alcools. Par exemple, il peut y avoir un article consacré à Alcools ou à Apollinaire et celui qui suit qui concerne un autre ouvrage (et a été gardé pour des raisons de recto verso). Par exemple, ce [folio](https://gallica.bnf.fr/ark:/12148/btv1b525088021/f149.item) ne concerne pas Alcools et seulement la première partie fait référence à un autre ouvrage d'Apollinaire.
Je pensais donc encoder les deux dernières rubriques qui concernent d'autres ouvrages et d'autres auteurs au strict minimum en utilisant uniquement `<lb>` `<p>`et `<head>` et ne pas faire de référencement pour l'index afin de ne pas porter à confusion. Qu'en pensez vous ?

**Comment by HugoSchtr** [comment]
Entièrement ok de mon côté !
