### ISSUE TITLE
Transfert d'attribut(s) de la div dans le cadre de l'encodage avec Group 

### ISSUE THREAD

**Issue by HugoSchtr** [axellelecroq/apollinaire-project#66]
Bonjour ! 

Suite à une review dans la PR #63 de @D0riane, et dans le cadre de l'encodage du dossier de presse avec Group, pensez-vous que certains des attributs de la div puissent être remontés plus haut dans l'arborescence ? 

En ayant en tête le cas où il y a plusieurs articles sur un seul folio, je pense qu'il serait utile de déplacer le ```@n``` initialement prévu pour la div, et de le mettre pour text. Les ```@xml:id``` peuvent rester dans les div à mon sens, de même que ```@type```, ces deux attributs donnant une information spécifique sur ce qui est présent à l'intérieur de la div. 

Text prendrait finalement le rôle d'indiquer quels sont les folios concernés, et la div l'article. 

Exemple :

```XML
<text n="162">
          <body>
               <div type="article" xml:id="article1_162">
                  <pb
                     facs="https://gallica.bnf.fr/ark:/12148/btv1b525088021/f162.item.r=Apollinaire%20manuscrits"/>
                    <!-- ENCODAGE -->
                 </div>
           </body>
</text>
```

De la sorte, l'attribut ```@n``` ne se répétera pas sur les différentes div d'un seul folio.

Nous pouvons également laisser les choses telles qu'elles le sont actuellement : 

```XML
<text>
          <body>
               <div type="article" n="162" xml:id="article1_162">
                  <pb
                     facs="https://gallica.bnf.fr/ark:/12148/btv1b525088021/f162.item.r=Apollinaire%20manuscrits"/>
                    <!-- ENCODAGE -->
                 </div>
           </body>
</text>
```

**Comment by D0riane** [comment]
Bonjour, 
`<text>` ferait ainsi référence à un folio ? 
Comment faire pour les articles qui du coup sont sur plusieurs folio ? Ils perdraient leur unité d' "article", non ?

**Comment by HugoSchtr** [comment]
Très juste. Je n'y avais pas pensé aha. 

Dans ce cas j'aurais tendance à dire qu'on reste sur notre chemin initial. :)

**Comment by D0riane** [comment]
Pour moi c'est le plus simple effectivement pour éviter de remettre en question toute la structure de l'encodage précédemment décidé. Si à la fin de l'encodage de l'ensemble du dossier de presse avec group, on se rendait compte d'une optimisation logique qui s'applique à tout le dossier, nous pourrons y réfléchir. Dans un premier temps, je serais d'avis donc de ne pas y toucher.

**Comment by leaprs** [comment]
Je suis d'accord avec @D0riane, je pense également qu'on y verra plus clair sur ces questions lorsqu'on aura un seul fichier pour tout le dossier de presse !
