### ISSUE TITLE
Forcer l'encodage du msDesc dans l'ODD

### ISSUE THREAD

**Issue by Juliettejns** [axellelecroq/apollinaire-project#71]
Bonjour à tous!

J'ouvre cette issue suite à la proposition de @PaulineChauvet, dans la PR #70, de forcer l'encodage du msDesc se trouvant dans la balise text (et qui doit apparaitre pour chaque poème encodé). 
```
          <msDesc>
                 <msIdentifier>
                            <repository>Bibliothèque nationale de France</repository>
                  </msIdentifier>
                   <physDesc>
                        <objectDesc>
                            <supportDesc>
                                <extent>1 page</extent>
                            </supportDesc>
                            <layoutDesc>
                                <layout columns="1">Strophes séparées par un saut de ligne et
                                        disposées sur une seule colonne.</layout>
                            </layoutDesc>
                        </objectDesc>
                    </physDesc>
           </msDesc>
```
Je propose l'encodage suivant, le msContents correspondant aux éléments contenus par le msDesc situé dans le teiheader:
```
                  <content>                     
                        <sequence>
                            <elementRef key="msIdentifier" minOccurs="1" maxOccurs="1"/>
                            <elementRef key="msContents" minOccurs="0" maxOccurs="1"/>
                            <elementRef key="physDesc" minOccurs="1" maxOccurs="1"/>
                        </sequence>
                    </content>
```
Cependant, je ne trouve pas que cela soit vraiment nécessaire, étant donné que ces éléments sont demandés par le schéma de base tei et on ne fait presque que répéter des règles préétablies. Autrement, il est peut être possible de conditionner l'emploi de ces balises avec un `<constraint>`. J'avoue que le temps que l'on risque de prendre pour paramètrer cette règle, qui me semble quelque peu superflue, me fait un peu peur. À discuter:)

**Comment by ArsGeo** [comment]
Effectivement, dans la mesure où c'est l'ordre habituel TEI je ne pense pas que ça soit nécessaire.
