### ISSUE TITLE
Problème transcription p173 dossierdepresse: nom de peintre

### ISSUE THREAD

**Issue by Juliettejns** [axellelecroq/apollinaire-project#8]
Bonjour tout le monde, 

Je travaille actuellement sur une lettre de Ferdinand Fleuret à Apollinaire datant du 30 mai 1913 et bute sur un mot.

Je lis "Votre Salomé est une estampe charmante de (Divier) ou d'Holbein;" et  n'arrive pas à trouver un nom de peintre correspondant à Divier.

Est-ce que vous auriez une idée?

Merci beaucoup!

![Screenshot_2021-01-02 Apollinaire Apollinaire Répertoire alphabétique utilisé pour confectionner le dossier de presse de l' (1)](https://user-images.githubusercontent.com/56683417/103461336-e8cbe900-4d1d-11eb-8f68-302b1f1629b2.png)

**Comment by AxelleL** [comment]
Diner peut-être ?

**Comment by D0riane** [comment]
Je lis également Dürer.

**Comment by Juliettejns** [comment]
Merci beaucoup!
